# frozen_string_literal: true

module Everyday
  class DockerfileGeneratorCalculator
    attr_reader :errors

    SUPPORTED_IMAGES = %w[ruby python node go java].freeze

    DEFAULT_VERSIONS = {
      "ruby" => "3.3",
      "python" => "3.12",
      "node" => "20",
      "go" => "1.22",
      "java" => "21"
    }.freeze

    DEFAULT_PORTS = {
      "ruby" => 3000,
      "python" => 8000,
      "node" => 3000,
      "go" => 8080,
      "java" => 8080
    }.freeze

    DEFAULT_COMMANDS = {
      "ruby" => "bundle exec rails server -b 0.0.0.0",
      "python" => "python manage.py runserver 0.0.0.0:8000",
      "node" => "node server.js",
      "go" => "./app",
      "java" => "java -jar app.jar"
    }.freeze

    def initialize(base_image:, version: "", app_dir: "/app", port: nil, command: "",
                   build_steps: [], env_vars: {}, copy_files: true, multi_stage: false)
      @base_image = base_image.to_s.strip.downcase
      @version = version.to_s.strip.presence || DEFAULT_VERSIONS.fetch(@base_image, "latest")
      @app_dir = app_dir.to_s.strip.presence || "/app"
      @port = port.present? ? port.to_i : DEFAULT_PORTS.fetch(@base_image, 3000)
      @command = command.to_s.strip.presence || DEFAULT_COMMANDS.fetch(@base_image, "echo 'No CMD specified'")
      @build_steps = normalize_build_steps(build_steps)
      @env_vars = normalize_env_vars(env_vars)
      @copy_files = ActiveModel::Type::Boolean.new.cast(copy_files)
      @multi_stage = ActiveModel::Type::Boolean.new.cast(multi_stage)
      @errors = []
    end

    def call
      validate!
      return { valid: false, errors: @errors } if @errors.any?

      dockerfile = build_dockerfile

      {
        valid: true,
        dockerfile: dockerfile,
        base_image: @base_image,
        version: @version,
        port: @port,
        multi_stage: @multi_stage,
        line_count: dockerfile.lines.count
      }
    end

    private

    def normalize_build_steps(steps)
      case steps
      when Array
        steps.map(&:to_s).map(&:strip).reject(&:empty?)
      when String
        steps.split("\n").map(&:strip).reject(&:empty?)
      else
        []
      end
    end

    def normalize_env_vars(vars)
      case vars
      when Hash
        vars.transform_keys(&:to_s).transform_values(&:to_s).reject { |k, v| k.blank? || v.blank? }
      else
        {}
      end
    end

    def validate!
      @errors << "Base image is required" if @base_image.blank?
      @errors << "Unsupported base image: #{@base_image}. Supported: #{SUPPORTED_IMAGES.join(', ')}" if @base_image.present? && !SUPPORTED_IMAGES.include?(@base_image)
      @errors << "Port must be between 1 and 65535" if @port < 1 || @port > 65_535
      @errors << "App directory is required" if @app_dir.blank?
    end

    def build_dockerfile
      if @multi_stage
        build_multi_stage_dockerfile
      else
        build_single_stage_dockerfile
      end
    end

    def build_single_stage_dockerfile
      lines = []

      lines << "# Dockerfile generated by CalcWise"
      lines << "FROM #{base_image_tag}"
      lines << ""

      # Environment variables
      if @env_vars.any?
        @env_vars.each { |key, value| lines << "ENV #{key}=#{value}" }
        lines << ""
      end

      lines << "WORKDIR #{@app_dir}"
      lines << ""

      # Copy dependency files first for layer caching
      lines.concat(dependency_copy_lines)

      # Install dependencies
      lines.concat(dependency_install_lines)

      # Copy application code
      if @copy_files
        lines << "COPY . ."
        lines << ""
      end

      # Custom build steps
      if @build_steps.any?
        @build_steps.each { |step| lines << "RUN #{step}" }
        lines << ""
      end

      lines << "EXPOSE #{@port}"
      lines << ""
      lines << "CMD #{format_cmd(@command)}"
      lines << ""

      lines.join("\n")
    end

    def build_multi_stage_dockerfile
      lines = []

      lines << "# Multi-stage Dockerfile generated by CalcWise"
      lines << ""
      lines << "# ---- Build Stage ----"
      lines << "FROM #{base_image_tag} AS builder"
      lines << ""
      lines << "WORKDIR #{@app_dir}"
      lines << ""

      # Copy dependency files
      lines.concat(dependency_copy_lines)

      # Install dependencies
      lines.concat(dependency_install_lines)

      # Copy and build
      if @copy_files
        lines << "COPY . ."
        lines << ""
      end

      if @build_steps.any?
        @build_steps.each { |step| lines << "RUN #{step}" }
        lines << ""
      end

      # Production stage
      lines << "# ---- Production Stage ----"
      lines << "FROM #{production_base_image} AS production"
      lines << ""

      if @env_vars.any?
        @env_vars.each { |key, value| lines << "ENV #{key}=#{value}" }
        lines << ""
      end

      lines << "WORKDIR #{@app_dir}"
      lines << ""
      lines.concat(production_copy_lines)
      lines << ""
      lines << "EXPOSE #{@port}"
      lines << ""
      lines << "CMD #{format_cmd(@command)}"
      lines << ""

      lines.join("\n")
    end

    def base_image_tag
      "#{@base_image}:#{@version}"
    end

    def production_base_image
      case @base_image
      when "ruby"  then "ruby:#{@version}-slim"
      when "python" then "python:#{@version}-slim"
      when "node"  then "node:#{@version}-slim"
      when "go"    then "alpine:3.19"
      when "java"  then "eclipse-temurin:#{@version}-jre"
      else
        base_image_tag
      end
    end

    def dependency_copy_lines
      lines = []
      case @base_image
      when "ruby"
        lines << "COPY Gemfile Gemfile.lock ./"
        lines << ""
      when "python"
        lines << "COPY requirements.txt ./"
        lines << ""
      when "node"
        lines << "COPY package.json package-lock.json* ./"
        lines << ""
      when "go"
        lines << "COPY go.mod go.sum ./"
        lines << ""
      when "java"
        lines << "COPY pom.xml ./"
        lines << ""
      end
      lines
    end

    def dependency_install_lines
      lines = []
      case @base_image
      when "ruby"
        lines << "RUN bundle install --without development test"
        lines << ""
      when "python"
        lines << "RUN pip install --no-cache-dir -r requirements.txt"
        lines << ""
      when "node"
        lines << "RUN npm ci --only=production"
        lines << ""
      when "go"
        lines << "RUN go mod download"
        lines << ""
      when "java"
        lines << "RUN mvn dependency:resolve"
        lines << ""
      end
      lines
    end

    def production_copy_lines
      case @base_image
      when "ruby"
        [ "COPY --from=builder #{@app_dir} #{@app_dir}" ]
      when "python"
        [
          "COPY --from=builder /usr/local/lib/python*/site-packages /usr/local/lib/python*/site-packages",
          "COPY --from=builder #{@app_dir} #{@app_dir}"
        ]
      when "node"
        [
          "COPY --from=builder #{@app_dir}/node_modules ./node_modules",
          "COPY --from=builder #{@app_dir} #{@app_dir}"
        ]
      when "go"
        [ "COPY --from=builder #{@app_dir}/app ." ]
      when "java"
        [ "COPY --from=builder #{@app_dir}/target/*.jar app.jar" ]
      else
        [ "COPY --from=builder #{@app_dir} #{@app_dir}" ]
      end
    end

    def format_cmd(command)
      parts = command.split(/\s+/)
      "[#{parts.map { |p| "\"#{p}\"" }.join(', ')}]"
    end
  end
end
