import { Controller } from "@hotwired/stimulus"

export default class extends Controller {
  static targets = [
    "baseImage", "version", "port", "appDir", "command",
    "multiStageCheckbox", "envVars", "buildSteps",
    "output", "error", "lineCount"
  ]

  static defaults = {
    ruby:   { version: "3.3",  port: 3000, cmd: "bundle exec rails server -b 0.0.0.0", dep_file: "Gemfile Gemfile.lock", install: "bundle install --without development test" },
    python: { version: "3.12", port: 8000, cmd: "python manage.py runserver 0.0.0.0:8000", dep_file: "requirements.txt", install: "pip install --no-cache-dir -r requirements.txt" },
    node:   { version: "20",   port: 3000, cmd: "node server.js", dep_file: "package.json package-lock.json*", install: "npm ci --only=production" },
    go:     { version: "1.22", port: 8080, cmd: "./app", dep_file: "go.mod go.sum", install: "go mod download" },
    java:   { version: "21",   port: 8080, cmd: "java -jar app.jar", dep_file: "pom.xml", install: "mvn dependency:resolve" }
  }

  static slimImages = {
    ruby: "ruby:VERSION-slim",
    python: "python:VERSION-slim",
    node: "node:VERSION-slim",
    go: "alpine:3.19",
    java: "eclipse-temurin:VERSION-jre"
  }

  connect() {
    this.fillDefaults()
  }

  fillDefaults() {
    const image = this.baseImageTarget.value
    const d = this.constructor.defaults[image]
    if (!d) return

    if (!this.versionTarget.value) this.versionTarget.value = d.version
    if (!this.portTarget.value) this.portTarget.value = d.port
    if (!this.commandTarget.value) this.commandTarget.value = d.cmd
  }

  changeImage() {
    const image = this.baseImageTarget.value
    const d = this.constructor.defaults[image]
    if (!d) return

    this.versionTarget.value = d.version
    this.portTarget.value = d.port
    this.commandTarget.value = d.cmd
  }

  generate() {
    const image = this.baseImageTarget.value
    const version = this.versionTarget.value.trim() || this.constructor.defaults[image]?.version || "latest"
    const port = parseInt(this.portTarget.value) || 3000
    const appDir = this.appDirTarget.value.trim() || "/app"
    const command = this.commandTarget.value.trim() || "echo 'No CMD'"
    const multiStage = this.multiStageCheckboxTarget.checked
    const envVarsRaw = this.envVarsTarget.value.trim()
    const buildStepsRaw = this.buildStepsTarget.value.trim()
    const d = this.constructor.defaults[image]

    // Validation
    const errors = []
    if (!image) errors.push("Base image is required")
    if (port < 1 || port > 65535) errors.push("Port must be between 1 and 65535")

    if (errors.length > 0) {
      this.errorTarget.textContent = errors.join(". ")
      this.errorTarget.classList.remove("hidden")
      this.outputTarget.value = ""
      this.lineCountTarget.textContent = ""
      return
    }

    this.errorTarget.classList.add("hidden")

    const lines = []
    const fromTag = `${image}:${version}`

    // Parse env vars
    const envLines = envVarsRaw ? envVarsRaw.split("\n").map(l => l.trim()).filter(l => l && l.includes("=")) : []
    // Parse build steps
    const buildSteps = buildStepsRaw ? buildStepsRaw.split("\n").map(l => l.trim()).filter(l => l) : []

    if (multiStage) {
      lines.push("# Multi-stage Dockerfile generated by Calc Hammer")
      lines.push("")
      lines.push("# ---- Build Stage ----")
      lines.push(`FROM ${fromTag} AS builder`)
      lines.push("")
      lines.push(`WORKDIR ${appDir}`)
      lines.push("")

      if (d) {
        lines.push(`COPY ${d.dep_file} ./`)
        lines.push("")
        lines.push(`RUN ${d.install}`)
        lines.push("")
      }

      lines.push("COPY . .")
      lines.push("")

      buildSteps.forEach(step => {
        lines.push(`RUN ${step}`)
      })
      if (buildSteps.length > 0) lines.push("")

      lines.push("# ---- Production Stage ----")
      const slimTemplate = this.constructor.slimImages[image] || `${image}:${version}-slim`
      const slimImage = slimTemplate.replace("VERSION", version)
      lines.push(`FROM ${slimImage} AS production`)
      lines.push("")

      envLines.forEach(env => lines.push(`ENV ${env}`))
      if (envLines.length > 0) lines.push("")

      lines.push(`WORKDIR ${appDir}`)
      lines.push("")
      lines.push(`COPY --from=builder ${appDir} ${appDir}`)
      lines.push("")
      lines.push(`EXPOSE ${port}`)
      lines.push("")
      lines.push(`CMD ${this.formatCmd(command)}`)
    } else {
      lines.push("# Dockerfile generated by Calc Hammer")
      lines.push(`FROM ${fromTag}`)
      lines.push("")

      envLines.forEach(env => lines.push(`ENV ${env}`))
      if (envLines.length > 0) lines.push("")

      lines.push(`WORKDIR ${appDir}`)
      lines.push("")

      if (d) {
        lines.push(`COPY ${d.dep_file} ./`)
        lines.push("")
        lines.push(`RUN ${d.install}`)
        lines.push("")
      }

      lines.push("COPY . .")
      lines.push("")

      buildSteps.forEach(step => {
        lines.push(`RUN ${step}`)
      })
      if (buildSteps.length > 0) lines.push("")

      lines.push(`EXPOSE ${port}`)
      lines.push("")
      lines.push(`CMD ${this.formatCmd(command)}`)
    }

    const dockerfile = lines.join("\n")
    this.outputTarget.value = dockerfile
    this.lineCountTarget.textContent = `${dockerfile.split("\n").length} lines`
  }

  formatCmd(command) {
    const parts = command.split(/\s+/)
    return `[${parts.map(p => `"${p}"`).join(", ")}]`
  }

  copy() {
    const text = this.outputTarget.value
    if (!text) return

    navigator.clipboard.writeText(text).then(() => {
      const btn = this.element.querySelector("[data-action*='copy']")
      if (btn) {
        const original = btn.textContent
        btn.textContent = "Copied!"
        setTimeout(() => { btn.textContent = original }, 1500)
      }
    })
  }
}
