import { Controller } from "@hotwired/stimulus"

export default class extends Controller {
  static targets = [
    "templateCheckbox", "output", "error", "lineCount", "templateCount"
  ]

  static templates = {
    ruby: `# Ruby / Rails
/.bundle
/vendor/bundle
/log/*
/tmp/*
/db/*.sqlite3
/db/*.sqlite3-journal
/public/assets
/public/packs
/storage/*
*.gem
.env
.env.local
.byebug_history
/config/master.key
/config/credentials/*.key`,
    python: `# Python
__pycache__/
*.py[cod]
*$py.class
*.so
venv/
.venv/
.env
dist/
build/
*.egg-info/
.eggs/
.mypy_cache/
.pytest_cache/
.coverage
htmlcov/`,
    node: `# Node.js
node_modules/
dist/
build/
.env
.env.local
.env.*.local
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.cache/
coverage/`,
    go: `# Go
/bin/
/vendor/
*.exe
*.exe~
*.dll
*.so
*.dylib
*.test
*.out
go.work`,
    java: `# Java
*.class
*.jar
*.war
*.ear
target/
.gradle/
build/
out/
.settings/
.classpath
.project
hs_err_pid*`,
    c_cpp: `# C / C++
*.o
*.obj
*.so
*.dylib
*.dll
*.exe
*.out
*.a
*.lib
*.d
build/
cmake-build-*/
CMakeFiles/
CMakeCache.txt`,
    rust: `# Rust
/target/
Cargo.lock
*.rs.bk
*.pdb`,
    php: `# PHP
/vendor/
composer.phar
.env
*.log
.phpunit.result.cache
.php-cs-fixer.cache
storage/framework/cache/*
storage/framework/sessions/*
storage/framework/views/*`,
    swift: `# Swift / Xcode
.build/
Packages/
xcuserdata/
DerivedData/
.swiftpm/
*.dSYM.zip
*.dSYM`,
    macos: `# macOS
.DS_Store
.AppleDouble
.LSOverride
._*
.Spotlight-V100
.Trashes`,
    windows: `# Windows
Thumbs.db
Thumbs.db:encryptable
ehthumbs.db
ehthumbs_vista.db
Desktop.ini
$RECYCLE.BIN/
*.lnk`,
    linux: `# Linux
*~
.fuse_hidden*
.directory
.Trash-*
.nfs*`,
    jetbrains: `# JetBrains IDEs
.idea/
*.iml
*.iws
*.ipr
out/
.idea_modules/`,
    vscode: `# VS Code
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
*.code-workspace`,
    vim: `# Vim
*.swp
*.swo
*.swn
*~
tags
Session.vim
.netrwhist`,
    emacs: `# Emacs
*~
\\#*\\#
.#*
*.elc
auto-save-list
tramp
.projectile
.dir-locals.el`
  }

  generate() {
    const selected = Array.from(this.templateCheckboxTargets)
      .filter(cb => cb.checked)
      .map(cb => cb.value)

    if (selected.length === 0) {
      this.errorTarget.textContent = "Select at least one template"
      this.errorTarget.classList.remove("hidden")
      this.outputTarget.value = ""
      this.lineCountTarget.textContent = ""
      this.templateCountTarget.textContent = ""
      return
    }

    this.errorTarget.classList.add("hidden")

    const header = `# Generated by CalcWise .gitignore Generator\n# Templates: ${selected.join(", ")}\n`
    const sections = selected
      .map(key => this.constructor.templates[key])
      .filter(Boolean)
      .join("\n\n")

    const content = header + "\n" + sections + "\n"
    this.outputTarget.value = content
    this.lineCountTarget.textContent = `${content.split("\n").length} lines`
    this.templateCountTarget.textContent = `${selected.length} template${selected.length === 1 ? "" : "s"}`
  }

  selectAll() {
    this.templateCheckboxTargets.forEach(cb => { cb.checked = true })
  }

  deselectAll() {
    this.templateCheckboxTargets.forEach(cb => { cb.checked = false })
  }

  copy() {
    const text = this.outputTarget.value
    if (!text) return

    navigator.clipboard.writeText(text).then(() => {
      const btn = this.element.querySelector("[data-action*='copy']")
      if (btn) {
        const original = btn.textContent
        btn.textContent = "Copied!"
        setTimeout(() => { btn.textContent = original }, 1500)
      }
    })
  }

  download() {
    const text = this.outputTarget.value
    if (!text) return

    const blob = new Blob([text], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = ".gitignore"
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }
}
