import { application } from "controllers/application"

// Finance calculators
import MortgageCalculatorController from "controllers/mortgage_calculator_controller"
import CompoundInterestCalculatorController from "controllers/compound_interest_calculator_controller"
import LoanCalculatorController from "controllers/loan_calculator_controller"
import InvestmentCalculatorController from "controllers/investment_calculator_controller"
import RetirementCalculatorController from "controllers/retirement_calculator_controller"
import PensionCalculatorController from "controllers/pension_calculator_controller"
import DebtPayoffCalculatorController from "controllers/debt_payoff_calculator_controller"
import SalaryCalculatorController from "controllers/salary_calculator_controller"
import SavingsGoalCalculatorController from "controllers/savings_goal_calculator_controller"
import RoiCalculatorController from "controllers/roi_calculator_controller"
import ProfitMarginCalculatorController from "controllers/profit_margin_calculator_controller"
import InflationCalculatorController from "controllers/inflation_calculator_controller"
import BreakEvenCalculatorController from "controllers/break_even_calculator_controller"
import MarkupMarginCalculatorController from "controllers/markup_margin_calculator_controller"
import RentVsBuyCalculatorController from "controllers/rent_vs_buy_calculator_controller"
import DividendYieldCalculatorController from "controllers/dividend_yield_calculator_controller"
import DcaCalculatorController from "controllers/dca_calculator_controller"
import SolarSavingsCalculatorController from "controllers/solar_savings_calculator_controller"
import TaxBracketCalculatorController from "controllers/tax_bracket_calculator_controller"
import AutoLoanCalculatorController from "controllers/auto_loan_calculator_controller"
import CreditCardPayoffCalculatorController from "controllers/credit_card_payoff_calculator_controller"
import NetWorthCalculatorController from "controllers/net_worth_calculator_controller"
import HomeAffordabilityCalculatorController from "controllers/home_affordability_calculator_controller"
import BusinessLoanCalculatorController from "controllers/business_loan_calculator_controller"
import CurrencyConverterCalculatorController from "controllers/currency_converter_calculator_controller"
import PaycheckCalculatorController from "controllers/paycheck_calculator_controller"
import FourOhOneKCalculatorController from "controllers/four_oh_one_k_calculator_controller"
import AmortizationCalculatorController from "controllers/amortization_calculator_controller"
import StockProfitCalculatorController from "controllers/stock_profit_calculator_controller"
import CdCalculatorController from "controllers/cd_calculator_controller"
import SavingsInterestCalculatorController from "controllers/savings_interest_calculator_controller"
import HouseFlipCalculatorController from "controllers/house_flip_calculator_controller"
import StudentLoanCalculatorController from "controllers/student_loan_calculator_controller"
import EstateTaxCalculatorController from "controllers/estate_tax_calculator_controller"
import CryptoProfitCalculatorController from "controllers/crypto_profit_calculator_controller"
import SimpleInterestCalculatorController from "controllers/simple_interest_calculator_controller"
import InvoiceGeneratorCalculatorController from "controllers/invoice_generator_calculator_controller"
import DetailedInvoiceGeneratorCalculatorController from "controllers/detailed_invoice_generator_calculator_controller"

// Math calculators
import PercentageCalculatorController from "controllers/percentage_calculator_controller"
import FractionCalculatorController from "controllers/fraction_calculator_controller"
import AreaCalculatorController from "controllers/area_calculator_controller"
import CircumferenceCalculatorController from "controllers/circumference_calculator_controller"
import ExponentCalculatorController from "controllers/exponent_calculator_controller"
import PythagoreanCalculatorController from "controllers/pythagorean_calculator_controller"
import QuadraticCalculatorController from "controllers/quadratic_calculator_controller"
import StandardDeviationCalculatorController from "controllers/standard_deviation_calculator_controller"
import GcdLcmCalculatorController from "controllers/gcd_lcm_calculator_controller"
import SampleSizeCalculatorController from "controllers/sample_size_calculator_controller"
import AspectRatioCalculatorController from "controllers/aspect_ratio_calculator_controller"
import MatrixCalculatorController from "controllers/matrix_calculator_controller"
import LogarithmCalculatorController from "controllers/logarithm_calculator_controller"
import ProbabilityCalculatorController from "controllers/probability_calculator_controller"
import PermutationCombinationCalculatorController from "controllers/permutation_combination_calculator_controller"
import MeanMedianModeCalculatorController from "controllers/mean_median_mode_calculator_controller"
import BaseConverterCalculatorController from "controllers/base_converter_calculator_controller"
import SigFigsCalculatorController from "controllers/sig_figs_calculator_controller"
import ScientificNotationCalculatorController from "controllers/scientific_notation_calculator_controller"
import IntegralCalculatorController from "controllers/integral_calculator_controller"
import ScientificCalculatorController from "controllers/scientific_calculator_controller"

// Physics calculators
import VelocityCalculatorController from "controllers/velocity_calculator_controller"
import ForceCalculatorController from "controllers/force_calculator_controller"
import KineticEnergyCalculatorController from "controllers/kinetic_energy_calculator_controller"
import OhmsLawCalculatorController from "controllers/ohms_law_calculator_controller"
import ProjectileMotionCalculatorController from "controllers/projectile_motion_calculator_controller"
import ElementMassCalculatorController from "controllers/element_mass_calculator_controller"
import ElementVolumeCalculatorController from "controllers/element_volume_calculator_controller"
import UnitConverterController from "controllers/unit_converter_controller"
import ElectricityCostCalculatorController from "controllers/electricity_cost_calculator_controller"
import WireGaugeCalculatorController from "controllers/wire_gauge_calculator_controller"
import DecibelCalculatorController from "controllers/decibel_calculator_controller"
import WavelengthFrequencyCalculatorController from "controllers/wavelength_frequency_calculator_controller"
import PlanetWeightCalculatorController from "controllers/planet_weight_calculator_controller"
import ResistorColorCodeCalculatorController from "controllers/resistor_color_code_calculator_controller"
import GearRatioCalculatorController from "controllers/gear_ratio_calculator_controller"
import PressureConverterCalculatorController from "controllers/pressure_converter_calculator_controller"
import HeatTransferCalculatorController from "controllers/heat_transfer_calculator_controller"
import SpringConstantCalculatorController from "controllers/spring_constant_calculator_controller"

// Health calculators
import BmiCalculatorController from "controllers/bmi_calculator_controller"
import CalorieCalculatorController from "controllers/calorie_calculator_controller"
import BodyFatCalculatorController from "controllers/body_fat_calculator_controller"
import PregnancyDueDateCalculatorController from "controllers/pregnancy_due_date_calculator_controller"
import TdeeCalculatorController from "controllers/tdee_calculator_controller"
import MacroCalculatorController from "controllers/macro_calculator_controller"
import PaceCalculatorController from "controllers/pace_calculator_controller"
import WaterIntakeCalculatorController from "controllers/water_intake_calculator_controller"
import SleepCalculatorController from "controllers/sleep_calculator_controller"
import OneRepMaxCalculatorController from "controllers/one_rep_max_calculator_controller"
import DogAgeCalculatorController from "controllers/dog_age_calculator_controller"
import PregnancyWeekCalculatorController from "controllers/pregnancy_week_calculator_controller"
import DogFoodCalculatorController from "controllers/dog_food_calculator_controller"
import IdealWeightCalculatorController from "controllers/ideal_weight_calculator_controller"
import BacCalculatorController from "controllers/bac_calculator_controller"
import ConceptionCalculatorController from "controllers/conception_calculator_controller"
import HeartRateZoneCalculatorController from "controllers/heart_rate_zone_calculator_controller"
import KetoCalculatorController from "controllers/keto_calculator_controller"
import IntermittentFastingCalculatorController from "controllers/intermittent_fasting_calculator_controller"
import OvulationCalculatorController from "controllers/ovulation_calculator_controller"
import BloodPressureCalculatorController from "controllers/blood_pressure_calculator_controller"
import LeanBodyMassCalculatorController from "controllers/lean_body_mass_calculator_controller"

// Contextual converters
import CostPerKmCalculatorController from "controllers/cost_per_km_calculator_controller"
import KwhToCostCalculatorController from "controllers/kwh_to_cost_calculator_controller"
import SalaryConverterCalculatorController from "controllers/salary_converter_calculator_controller"
import RentPerSqmCalculatorController from "controllers/rent_per_sqm_calculator_controller"
import PricePerWeightCalculatorController from "controllers/price_per_weight_calculator_controller"
import FuelCostTripCalculatorController from "controllers/fuel_cost_trip_calculator_controller"
import CostOfLivingCalculatorController from "controllers/cost_of_living_calculator_controller"
import DataUsageCostCalculatorController from "controllers/data_usage_cost_calculator_controller"
import HourlyToProjectCalculatorController from "controllers/hourly_to_project_calculator_controller"
import SqftCostCalculatorController from "controllers/sqft_cost_calculator_controller"
import CostPerClickCalculatorController from "controllers/cost_per_click_calculator_controller"
import CostPerLeadCalculatorController from "controllers/cost_per_lead_calculator_controller"
import CostPerAcquisitionCalculatorController from "controllers/cost_per_acquisition_calculator_controller"
import RevenuePerEmployeeCalculatorController from "controllers/revenue_per_employee_calculator_controller"
import EarningsPerShareCalculatorController from "controllers/earnings_per_share_calculator_controller"
import SavingsPerMonthCalculatorController from "controllers/savings_per_month_calculator_controller"
import CostPerPersonCalculatorController from "controllers/cost_per_person_calculator_controller"
import CostPerDayCalculatorController from "controllers/cost_per_day_calculator_controller"
import CostPerHourCalculatorController from "controllers/cost_per_hour_calculator_controller"
import CostPerServingCalculatorController from "controllers/cost_per_serving_calculator_controller"
import CostPerWearCalculatorController from "controllers/cost_per_wear_calculator_controller"
import CostPerPageCalculatorController from "controllers/cost_per_page_calculator_controller"
import PricePerLiterCalculatorController from "controllers/price_per_liter_calculator_controller"
import WordsPerMinuteCalculatorController from "controllers/words_per_minute_calculator_controller"
import CostPerMileCalculatorController from "controllers/cost_per_mile_calculator_controller"
import CaloriesPerServingCalculatorController from "controllers/calories_per_serving_calculator_controller"
import ProteinPerMealCalculatorController from "controllers/protein_per_meal_calculator_controller"
import CaloriesPer100gCalculatorController from "controllers/calories_per_100g_calculator_controller"
import StepsPerMileCalculatorController from "controllers/steps_per_mile_calculator_controller"
import PricePerSqmCalculatorController from "controllers/price_per_sqm_calculator_controller"
import WorkHoursCalculatorController from "controllers/work_hours_calculator_controller"
import OvertimeCalculatorController from "controllers/overtime_calculator_controller"
import ShiftDurationCalculatorController from "controllers/shift_duration_calculator_controller"
import DaysUntilCalculatorController from "controllers/days_until_calculator_controller"
import BusinessDaysCalculatorController from "controllers/business_days_calculator_controller"
import TimeCardCalculatorController from "controllers/time_card_calculator_controller"
import HourlyToSalaryCalculatorController from "controllers/hourly_to_salary_calculator_controller"
import WorkBreakCalculatorController from "controllers/work_break_calculator_controller"
import WordCounterCalculatorController from "controllers/word_counter_calculator_controller"
import CharacterCounterCalculatorController from "controllers/character_counter_calculator_controller"
import CaseConverterCalculatorController from "controllers/case_converter_calculator_controller"
import RemoveDuplicatesCalculatorController from "controllers/remove_duplicates_calculator_controller"
import JsonFormatterCalculatorController from "controllers/json_formatter_calculator_controller"
import LoremIpsumCalculatorController from "controllers/lorem_ipsum_calculator_controller"
import TextDiffCalculatorController from "controllers/text_diff_calculator_controller"
import StringEncoderCalculatorController from "controllers/string_encoder_calculator_controller"
import RegexTesterCalculatorController from "controllers/regex_tester_calculator_controller"
import MarkdownPreviewCalculatorController from "controllers/markdown_preview_calculator_controller"
import SecureRandomCalculatorController from "controllers/secure_random_calculator_controller"
import UuidGeneratorCalculatorController from "controllers/uuid_generator_calculator_controller"
import HashGeneratorCalculatorController from "controllers/hash_generator_calculator_controller"
import HmacGeneratorCalculatorController from "controllers/hmac_generator_calculator_controller"
import JwtDecoderCalculatorController from "controllers/jwt_decoder_calculator_controller"
import SqlFormatterCalculatorController from "controllers/sql_formatter_calculator_controller"
import CronParserCalculatorController from "controllers/cron_parser_calculator_controller"
import CronBuilderCalculatorController from "controllers/cron_builder_calculator_controller"
import ColorConverterCalculatorController from "controllers/color_converter_calculator_controller"
import UrlParserCalculatorController from "controllers/url_parser_calculator_controller"
import HttpHeaderParserCalculatorController from "controllers/http_header_parser_calculator_controller"
import SubnetCalculatorController from "controllers/subnet_calculator_controller"
import UnixTimestampCalculatorController from "controllers/unix_timestamp_calculator_controller"
import YamlToJsonCalculatorController from "controllers/yaml_to_json_calculator_controller"
import CsvToJsonCalculatorController from "controllers/csv_to_json_calculator_controller"
import XmlToJsonCalculatorController from "controllers/xml_to_json_calculator_controller"
import HtmlEntityEncoderCalculatorController from "controllers/html_entity_encoder_calculator_controller"
import CodeMinifierCalculatorController from "controllers/code_minifier_calculator_controller"
import EscapeUnescapeCalculatorController from "controllers/escape_unescape_calculator_controller"
import CsvToExcelCalculatorController from "controllers/csv_to_excel_calculator_controller"
import ExcelToCsvCalculatorController from "controllers/excel_to_csv_calculator_controller"
import MarkdownToHtmlCalculatorController from "controllers/markdown_to_html_calculator_controller"
import HtmlToMarkdownCalculatorController from "controllers/html_to_markdown_calculator_controller"
import TxtToPdfCalculatorController from "controllers/txt_to_pdf_calculator_controller"
import CsvToPdfCalculatorController from "controllers/csv_to_pdf_calculator_controller"
import MarkdownToPdfCalculatorController from "controllers/markdown_to_pdf_calculator_controller"
import ExcelToPdfCalculatorController from "controllers/excel_to_pdf_calculator_controller"
import DocxToPdfCalculatorController from "controllers/docx_to_pdf_calculator_controller"
import ColorPalettePickerCalculatorController from "controllers/color_palette_picker_calculator_controller"
import PasswordGeneratorCalculatorController from "controllers/password_generator_calculator_controller"
import CspBuilderCalculatorController from "controllers/csp_builder_calculator_controller"
import ChmodCalculatorController from "controllers/chmod_calculator_controller"
import PortReferenceCalculatorController from "controllers/port_reference_calculator_controller"
import QrCodeGeneratorCalculatorController from "controllers/qr_code_generator_calculator_controller"
import Base64ImageEncoderCalculatorController from "controllers/base64_image_encoder_calculator_controller"
import MarkdownTableGeneratorCalculatorController from "controllers/markdown_table_generator_calculator_controller"
import JsonToCsvCalculatorController from "controllers/json_to_csv_calculator_controller"
import NginxConfigGeneratorCalculatorController from "controllers/nginx_config_generator_calculator_controller"
import DockerfileGeneratorCalculatorController from "controllers/dockerfile_generator_calculator_controller"
import GitignoreGeneratorCalculatorController from "controllers/gitignore_generator_calculator_controller"
import EnvValidatorCalculatorController from "controllers/env_validator_calculator_controller"
import RegexBuilderCalculatorController from "controllers/regex_builder_calculator_controller"
import CorsCheckerCalculatorController from "controllers/cors_checker_calculator_controller"
import SslCertDecoderCalculatorController from "controllers/ssl_cert_decoder_calculator_controller"
import IpLookupCalculatorController from "controllers/ip_lookup_calculator_controller"
import DnsLookupCalculatorController from "controllers/dns_lookup_calculator_controller"
import MacLookupCalculatorController from "controllers/mac_lookup_calculator_controller"
import OdtToDocxCalculatorController from "controllers/odt_to_docx_calculator_controller"
import OdtToPdfCalculatorController from "controllers/odt_to_pdf_calculator_controller"
import DocxToOdtCalculatorController from "controllers/docx_to_odt_calculator_controller"

import AlarmTimerCalculatorController from "controllers/alarm_timer_calculator_controller"
import AlarmClockCalculatorController from "controllers/alarm_clock_calculator_controller"
import AlarmClockActiveCalculatorController from "controllers/alarm_clock_active_calculator_controller"
import StopwatchCalculatorController from "controllers/stopwatch_calculator_controller"
import PomodoroTimerCalculatorController from "controllers/pomodoro_timer_calculator_controller"
import TextToSpeechCalculatorController from "controllers/text_to_speech_calculator_controller"

import TemperatureConverterCalculatorController from "controllers/temperature_converter_calculator_controller"
import LengthConverterCalculatorController from "controllers/length_converter_calculator_controller"
import WeightConverterCalculatorController from "controllers/weight_converter_calculator_controller"
import SpeedConverterCalculatorController from "controllers/speed_converter_calculator_controller"
import ByteConverterCalculatorController from "controllers/byte_converter_calculator_controller"
import CupConverterCalculatorController from "controllers/cup_converter_calculator_controller"
import VolumeConverterCalculatorController from "controllers/volume_converter_calculator_controller"

import CalorieTrackerController from "controllers/calorie_tracker_controller"
import CalorieTrackerSummaryController from "controllers/calorie_tracker_summary_controller"

import CssBoxShadowCalculatorController from "controllers/css_box_shadow_calculator_controller"
import CssFlexboxCalculatorController from "controllers/css_flexbox_calculator_controller"
import PxToRemCalculatorController from "controllers/px_to_rem_calculator_controller"
import MetaTagGeneratorCalculatorController from "controllers/meta_tag_generator_calculator_controller"
import FaviconGeneratorCalculatorController from "controllers/favicon_generator_calculator_controller"

import SchemaGeneratorCalculatorController from "controllers/schema_generator_calculator_controller"
import KeywordDensityCalculatorController from "controllers/keyword_density_calculator_controller"
import PrimeCheckerCalculatorController from "controllers/prime_checker_calculator_controller"
import RandomNumberCalculatorController from "controllers/random_number_calculator_controller"
import ImageResizerCalculatorController from "controllers/image_resizer_calculator_controller"

import MorseCodeCalculatorController from "controllers/morse_code_calculator_controller"
import RomanNumeralCalculatorController from "controllers/roman_numeral_calculator_controller"
import FakeDataGeneratorCalculatorController from "controllers/fake_data_generator_calculator_controller"
import BarcodeGeneratorCalculatorController from "controllers/barcode_generator_calculator_controller"

// IT tools
import HttpStatusReferenceCalculatorController from "controllers/http_status_reference_calculator_controller"
import OgPreviewCalculatorController from "controllers/og_preview_calculator_controller"
import CurlToCodeCalculatorController from "controllers/curl_to_code_calculator_controller"
import JsonToYamlCalculatorController from "controllers/json_to_yaml_calculator_controller"
import JsonToTypescriptCalculatorController from "controllers/json_to_typescript_calculator_controller"
import HtmlFormatterCalculatorController from "controllers/html_formatter_calculator_controller"
import CssFormatterCalculatorController from "controllers/css_formatter_calculator_controller"
import JsFormatterCalculatorController from "controllers/js_formatter_calculator_controller"
import HtmlToJsxCalculatorController from "controllers/html_to_jsx_calculator_controller"
import RobotsTxtCalculatorController from "controllers/robots_txt_calculator_controller"
import SvgToPngCalculatorController from "controllers/svg_to_png_calculator_controller"
import Base64EncoderCalculatorController from "controllers/base64_encoder_calculator_controller"
import UrlEncoderCalculatorController from "controllers/url_encoder_calculator_controller"
import HexAsciiCalculatorController from "controllers/hex_ascii_calculator_controller"

// Construction calculators
import PaintCalculatorController from "controllers/paint_calculator_controller"
import FlooringCalculatorController from "controllers/flooring_calculator_controller"
import ConcreteCalculatorController from "controllers/concrete_calculator_controller"
import GravelMulchCalculatorController from "controllers/gravel_mulch_calculator_controller"
import FenceCalculatorController from "controllers/fence_calculator_controller"
import RoofingCalculatorController from "controllers/roofing_calculator_controller"
import StaircaseCalculatorController from "controllers/staircase_calculator_controller"
import DeckCalculatorController from "controllers/deck_calculator_controller"
import WallpaperCalculatorController from "controllers/wallpaper_calculator_controller"
import TileCalculatorController from "controllers/tile_calculator_controller"
import LumberCalculatorController from "controllers/lumber_calculator_controller"
import MiterAngleCalculatorController from "controllers/miter_angle_calculator_controller"
import WoodMoistureCalculatorController from "controllers/wood_moisture_calculator_controller"
import WoodShrinkageCalculatorController from "controllers/wood_shrinkage_calculator_controller"
import WoodWeightCalculatorController from "controllers/wood_weight_calculator_controller"
import RipCutCalculatorController from "controllers/rip_cut_calculator_controller"
import CabinetDoorCalculatorController from "controllers/cabinet_door_calculator_controller"
// Textile calculators
import FabricYardageCalculatorController from "controllers/fabric_yardage_calculator_controller"
import SeamAllowanceCalculatorController from "controllers/seam_allowance_calculator_controller"
import KnittingGaugeCalculatorController from "controllers/knitting_gauge_calculator_controller"
import CrochetGaugeCalculatorController from "controllers/crochet_gauge_calculator_controller"
import NeedleHookSizeCalculatorController from "controllers/needle_hook_size_calculator_controller"
import YarnYardageCalculatorController from "controllers/yarn_yardage_calculator_controller"
import QuiltBackingCalculatorController from "controllers/quilt_backing_calculator_controller"
import HalfSquareTriangleCalculatorController from "controllers/half_square_triangle_calculator_controller"
import BindingStripsCalculatorController from "controllers/binding_strips_calculator_controller"
import FabricGsmCalculatorController from "controllers/fabric_gsm_calculator_controller"
import FabricShrinkageCalculatorController from "controllers/fabric_shrinkage_calculator_controller"
import CrossStitchFabricCalculatorController from "controllers/cross_stitch_fabric_calculator_controller"
import HvacBtuCalculatorController from "controllers/hvac_btu_calculator_controller"

// Alcohol & Brewing calculators
import AbvCalculatorController from "controllers/abv_calculator_controller"
import IbuCalculatorController from "controllers/ibu_calculator_controller"
import SrmCalculatorController from "controllers/srm_calculator_controller"
import StrikeWaterCalculatorController from "controllers/strike_water_calculator_controller"
import HydrometerCorrectionCalculatorController from "controllers/hydrometer_correction_calculator_controller"
import BrixToGravityCalculatorController from "controllers/brix_to_gravity_calculator_controller"
import YeastPitchCalculatorController from "controllers/yeast_pitch_calculator_controller"
import PrimingSugarCalculatorController from "controllers/priming_sugar_calculator_controller"
import KegForceCarbonationCalculatorController from "controllers/keg_force_carbonation_calculator_controller"
import DistillerProofingCalculatorController from "controllers/distiller_proofing_calculator_controller"
import CocktailAbvCalculatorController from "controllers/cocktail_abv_calculator_controller"
import PourCostCalculatorController from "controllers/pour_cost_calculator_controller"

// Geography calculators
import CoordinateDistanceCalculatorController from "controllers/coordinate_distance_calculator_controller"
import LatitudeLongitudeConverterController from "controllers/latitude_longitude_converter_controller"
import BearingCalculatorController from "controllers/bearing_calculator_controller"
import MidpointCalculatorController from "controllers/midpoint_calculator_controller"
import MapScaleCalculatorController from "controllers/map_scale_calculator_controller"
import PopulationDensityCalculatorController from "controllers/population_density_calculator_controller"
import DestinationPointCalculatorController from "controllers/destination_point_calculator_controller"
import AntipodeCalculatorController from "controllers/antipode_calculator_controller"
import RhumbLineCalculatorController from "controllers/rhumb_line_calculator_controller"
import PolygonAreaCalculatorController from "controllers/polygon_area_calculator_controller"
import HikingTimeCalculatorController from "controllers/hiking_time_calculator_controller"
import GeohashConverterController from "controllers/geohash_converter_controller"
import DegreesToKilometersConverterController from "controllers/degrees_to_kilometers_converter_controller"
import FlightTimeCalculatorController from "controllers/flight_time_calculator_controller"

// Gardening calculators
import MulchCalculatorController from "controllers/mulch_calculator_controller"
import TopsoilCalculatorController from "controllers/topsoil_calculator_controller"
import RaisedBedSoilCalculatorController from "controllers/raised_bed_soil_calculator_controller"
import CompostCalculatorController from "controllers/compost_calculator_controller"
import FertilizerCalculatorController from "controllers/fertilizer_calculator_controller"
import GrassSeedCalculatorController from "controllers/grass_seed_calculator_controller"
import LawnWateringCalculatorController from "controllers/lawn_watering_calculator_controller"
import PlantSpacingCalculatorController from "controllers/plant_spacing_calculator_controller"
import GrowingDegreeDaysCalculatorController from "controllers/growing_degree_days_calculator_controller"
import TreeAgeCalculatorController from "controllers/tree_age_calculator_controller"
import GreenhouseHeaterCalculatorController from "controllers/greenhouse_heater_calculator_controller"
import CompostRatioCalculatorController from "controllers/compost_ratio_calculator_controller"

// Everyday calculators
import TipCalculatorController from "controllers/tip_calculator_controller"
import DiscountCalculatorController from "controllers/discount_calculator_controller"
import AgeCalculatorController from "controllers/age_calculator_controller"
import DateDifferenceCalculatorController from "controllers/date_difference_calculator_controller"
import GasMileageCalculatorController from "controllers/gas_mileage_calculator_controller"
import FuelCostCalculatorController from "controllers/fuel_cost_calculator_controller"
import GpaCalculatorController from "controllers/gpa_calculator_controller"
import CookingConverterController from "controllers/cooking_converter_controller"
import TimeZoneConverterCalculatorController from "controllers/time_zone_converter_calculator_controller"
import ShoeSizeCalculatorController from "controllers/shoe_size_calculator_controller"
import GradeCalculatorController from "controllers/grade_calculator_controller"
import ElectricityBillCalculatorController from "controllers/electricity_bill_calculator_controller"
import MovingCostCalculatorController from "controllers/moving_cost_calculator_controller"
import PasswordStrengthCalculatorController from "controllers/password_strength_calculator_controller"
import ScreenSizeCalculatorController from "controllers/screen_size_calculator_controller"
import BandwidthCalculatorController from "controllers/bandwidth_calculator_controller"
import UnitPriceCalculatorController from "controllers/unit_price_calculator_controller"

// Suite controllers
import SuiteStepperController from "controllers/suite_stepper_controller"

// UI controllers
import DarkModeController from "controllers/dark_mode_controller"
import NavbarController from "controllers/navbar_controller"
import CalculatorSearchController from "controllers/calculator_search_controller"
import CookieConsentController from "controllers/cookie_consent_controller"
import AdEngagementController from "controllers/ad_engagement_controller"
import CalculatorRatingController from "controllers/calculator_rating_controller"
import ChartController from "controllers/chart_controller"
import EmailCaptureController from "controllers/email_capture_controller"
import TrackVisitController from "controllers/track_visit_controller"
import RecentCalculatorsController from "controllers/recent_calculators_controller"
import FavoriteController from "controllers/favorite_controller"
import CsvExportController from "controllers/csv_export_controller"
import CalculationHistoryController from "controllers/calculation_history_controller"

// Finance
application.register("mortgage-calculator", MortgageCalculatorController)
application.register("compound-interest-calculator", CompoundInterestCalculatorController)
application.register("loan-calculator", LoanCalculatorController)
application.register("investment-calculator", InvestmentCalculatorController)
application.register("retirement-calculator", RetirementCalculatorController)
application.register("pension-calculator", PensionCalculatorController)
application.register("debt-payoff-calculator", DebtPayoffCalculatorController)
application.register("salary-calculator", SalaryCalculatorController)
application.register("savings-goal-calculator", SavingsGoalCalculatorController)
application.register("roi-calculator", RoiCalculatorController)
application.register("profit-margin-calculator", ProfitMarginCalculatorController)
application.register("inflation-calculator", InflationCalculatorController)
application.register("break-even-calculator", BreakEvenCalculatorController)
application.register("markup-margin-calculator", MarkupMarginCalculatorController)
application.register("rent-vs-buy-calculator", RentVsBuyCalculatorController)
application.register("dividend-yield-calculator", DividendYieldCalculatorController)
application.register("dca-calculator", DcaCalculatorController)
application.register("solar-savings-calculator", SolarSavingsCalculatorController)
application.register("tax-bracket-calculator", TaxBracketCalculatorController)
application.register("auto-loan-calculator", AutoLoanCalculatorController)
application.register("credit-card-payoff-calculator", CreditCardPayoffCalculatorController)
application.register("net-worth-calculator", NetWorthCalculatorController)
application.register("home-affordability-calculator", HomeAffordabilityCalculatorController)
application.register("business-loan-calculator", BusinessLoanCalculatorController)
application.register("currency-converter-calculator", CurrencyConverterCalculatorController)
application.register("paycheck-calculator", PaycheckCalculatorController)
application.register("four-oh-one-k-calculator", FourOhOneKCalculatorController)
application.register("amortization-calculator", AmortizationCalculatorController)
application.register("stock-profit-calculator", StockProfitCalculatorController)
application.register("cd-calculator", CdCalculatorController)
application.register("savings-interest-calculator", SavingsInterestCalculatorController)
application.register("house-flip-calculator", HouseFlipCalculatorController)
application.register("student-loan-calculator", StudentLoanCalculatorController)
application.register("estate-tax-calculator", EstateTaxCalculatorController)
application.register("crypto-profit-calculator", CryptoProfitCalculatorController)
application.register("simple-interest-calculator", SimpleInterestCalculatorController)
application.register("invoice-generator-calculator", InvoiceGeneratorCalculatorController)
application.register("detailed-invoice-generator-calculator", DetailedInvoiceGeneratorCalculatorController)

// Math
application.register("percentage-calculator", PercentageCalculatorController)
application.register("fraction-calculator", FractionCalculatorController)
application.register("area-calculator", AreaCalculatorController)
application.register("circumference-calculator", CircumferenceCalculatorController)
application.register("exponent-calculator", ExponentCalculatorController)
application.register("pythagorean-calculator", PythagoreanCalculatorController)
application.register("quadratic-calculator", QuadraticCalculatorController)
application.register("standard-deviation-calculator", StandardDeviationCalculatorController)
application.register("gcd-lcm-calculator", GcdLcmCalculatorController)
application.register("sample-size-calculator", SampleSizeCalculatorController)
application.register("aspect-ratio-calculator", AspectRatioCalculatorController)
application.register("matrix-calculator", MatrixCalculatorController)
application.register("logarithm-calculator", LogarithmCalculatorController)
application.register("probability-calculator", ProbabilityCalculatorController)
application.register("permutation-combination-calculator", PermutationCombinationCalculatorController)
application.register("mean-median-mode-calculator", MeanMedianModeCalculatorController)
application.register("base-converter-calculator", BaseConverterCalculatorController)
application.register("sig-figs-calculator", SigFigsCalculatorController)
application.register("scientific-notation-calculator", ScientificNotationCalculatorController)
application.register("scientific-calculator", ScientificCalculatorController)
application.register("integral-calculator", IntegralCalculatorController)

// Physics
application.register("velocity-calculator", VelocityCalculatorController)
application.register("force-calculator", ForceCalculatorController)
application.register("kinetic-energy-calculator", KineticEnergyCalculatorController)
application.register("ohms-law-calculator", OhmsLawCalculatorController)
application.register("projectile-motion-calculator", ProjectileMotionCalculatorController)
application.register("element-mass-calculator", ElementMassCalculatorController)
application.register("element-volume-calculator", ElementVolumeCalculatorController)
application.register("unit-converter", UnitConverterController)
application.register("electricity-cost-calculator", ElectricityCostCalculatorController)
application.register("wire-gauge-calculator", WireGaugeCalculatorController)
application.register("decibel-calculator", DecibelCalculatorController)
application.register("wavelength-frequency-calculator", WavelengthFrequencyCalculatorController)
application.register("planet-weight-calculator", PlanetWeightCalculatorController)
application.register("resistor-color-code-calculator", ResistorColorCodeCalculatorController)
application.register("gear-ratio-calculator", GearRatioCalculatorController)
application.register("pressure-converter-calculator", PressureConverterCalculatorController)
application.register("heat-transfer-calculator", HeatTransferCalculatorController)
application.register("spring-constant-calculator", SpringConstantCalculatorController)

// Health
application.register("bmi-calculator", BmiCalculatorController)
application.register("calorie-calculator", CalorieCalculatorController)
application.register("body-fat-calculator", BodyFatCalculatorController)
application.register("pregnancy-due-date-calculator", PregnancyDueDateCalculatorController)
application.register("tdee-calculator", TdeeCalculatorController)
application.register("macro-calculator", MacroCalculatorController)
application.register("pace-calculator", PaceCalculatorController)
application.register("water-intake-calculator", WaterIntakeCalculatorController)
application.register("sleep-calculator", SleepCalculatorController)
application.register("one-rep-max-calculator", OneRepMaxCalculatorController)
application.register("dog-age-calculator", DogAgeCalculatorController)
application.register("pregnancy-week-calculator", PregnancyWeekCalculatorController)
application.register("dog-food-calculator", DogFoodCalculatorController)
application.register("ideal-weight-calculator", IdealWeightCalculatorController)
application.register("bac-calculator", BacCalculatorController)
application.register("conception-calculator", ConceptionCalculatorController)
application.register("heart-rate-zone-calculator", HeartRateZoneCalculatorController)
application.register("keto-calculator", KetoCalculatorController)
application.register("intermittent-fasting-calculator", IntermittentFastingCalculatorController)
application.register("ovulation-calculator", OvulationCalculatorController)
application.register("blood-pressure-calculator", BloodPressureCalculatorController)
application.register("lean-body-mass-calculator", LeanBodyMassCalculatorController)

// Contextual converters
application.register("cost-per-km-calculator", CostPerKmCalculatorController)
application.register("kwh-to-cost-calculator", KwhToCostCalculatorController)
application.register("salary-converter-calculator", SalaryConverterCalculatorController)
application.register("rent-per-sqm-calculator", RentPerSqmCalculatorController)
application.register("price-per-weight-calculator", PricePerWeightCalculatorController)
application.register("fuel-cost-trip-calculator", FuelCostTripCalculatorController)
application.register("cost-of-living-calculator", CostOfLivingCalculatorController)
application.register("data-usage-cost-calculator", DataUsageCostCalculatorController)
application.register("hourly-to-project-calculator", HourlyToProjectCalculatorController)
application.register("sqft-cost-calculator", SqftCostCalculatorController)
application.register("cost-per-click-calculator", CostPerClickCalculatorController)
application.register("cost-per-lead-calculator", CostPerLeadCalculatorController)
application.register("cost-per-acquisition-calculator", CostPerAcquisitionCalculatorController)
application.register("revenue-per-employee-calculator", RevenuePerEmployeeCalculatorController)
application.register("earnings-per-share-calculator", EarningsPerShareCalculatorController)
application.register("savings-per-month-calculator", SavingsPerMonthCalculatorController)
application.register("cost-per-person-calculator", CostPerPersonCalculatorController)
application.register("cost-per-day-calculator", CostPerDayCalculatorController)
application.register("cost-per-hour-calculator", CostPerHourCalculatorController)
application.register("cost-per-serving-calculator", CostPerServingCalculatorController)
application.register("cost-per-wear-calculator", CostPerWearCalculatorController)
application.register("cost-per-page-calculator", CostPerPageCalculatorController)
application.register("price-per-liter-calculator", PricePerLiterCalculatorController)
application.register("words-per-minute-calculator", WordsPerMinuteCalculatorController)
application.register("cost-per-mile-calculator", CostPerMileCalculatorController)
application.register("calories-per-serving-calculator", CaloriesPerServingCalculatorController)
application.register("protein-per-meal-calculator", ProteinPerMealCalculatorController)
application.register("calories-per-100g-calculator", CaloriesPer100gCalculatorController)
application.register("steps-per-mile-calculator", StepsPerMileCalculatorController)
application.register("price-per-sqm-calculator", PricePerSqmCalculatorController)
application.register("work-hours-calculator", WorkHoursCalculatorController)
application.register("overtime-calculator", OvertimeCalculatorController)
application.register("shift-duration-calculator", ShiftDurationCalculatorController)
application.register("days-until-calculator", DaysUntilCalculatorController)
application.register("business-days-calculator", BusinessDaysCalculatorController)
application.register("time-card-calculator", TimeCardCalculatorController)
application.register("hourly-to-salary-calculator", HourlyToSalaryCalculatorController)
application.register("work-break-calculator", WorkBreakCalculatorController)
application.register("word-counter-calculator", WordCounterCalculatorController)
application.register("character-counter-calculator", CharacterCounterCalculatorController)
application.register("case-converter-calculator", CaseConverterCalculatorController)
application.register("remove-duplicates-calculator", RemoveDuplicatesCalculatorController)
application.register("json-formatter-calculator", JsonFormatterCalculatorController)
application.register("lorem-ipsum-calculator", LoremIpsumCalculatorController)
application.register("text-diff-calculator", TextDiffCalculatorController)
application.register("string-encoder-calculator", StringEncoderCalculatorController)
application.register("regex-tester-calculator", RegexTesterCalculatorController)
application.register("markdown-preview-calculator", MarkdownPreviewCalculatorController)

// Construction
application.register("paint-calculator", PaintCalculatorController)
application.register("flooring-calculator", FlooringCalculatorController)
application.register("concrete-calculator", ConcreteCalculatorController)
application.register("gravel-mulch-calculator", GravelMulchCalculatorController)
application.register("fence-calculator", FenceCalculatorController)
application.register("roofing-calculator", RoofingCalculatorController)
application.register("staircase-calculator", StaircaseCalculatorController)
application.register("deck-calculator", DeckCalculatorController)
application.register("wallpaper-calculator", WallpaperCalculatorController)
application.register("tile-calculator", TileCalculatorController)
application.register("lumber-calculator", LumberCalculatorController)
application.register("miter-angle-calculator", MiterAngleCalculatorController)
application.register("wood-moisture-calculator", WoodMoistureCalculatorController)
application.register("wood-shrinkage-calculator", WoodShrinkageCalculatorController)
application.register("wood-weight-calculator", WoodWeightCalculatorController)
application.register("rip-cut-calculator", RipCutCalculatorController)
application.register("cabinet-door-calculator", CabinetDoorCalculatorController)
// Textile calculators
application.register("fabric-yardage-calculator", FabricYardageCalculatorController)
application.register("seam-allowance-calculator", SeamAllowanceCalculatorController)
application.register("knitting-gauge-calculator", KnittingGaugeCalculatorController)
application.register("crochet-gauge-calculator", CrochetGaugeCalculatorController)
application.register("needle-hook-size-calculator", NeedleHookSizeCalculatorController)
application.register("yarn-yardage-calculator", YarnYardageCalculatorController)
application.register("quilt-backing-calculator", QuiltBackingCalculatorController)
application.register("half-square-triangle-calculator", HalfSquareTriangleCalculatorController)
application.register("binding-strips-calculator", BindingStripsCalculatorController)
application.register("fabric-gsm-calculator", FabricGsmCalculatorController)
application.register("fabric-shrinkage-calculator", FabricShrinkageCalculatorController)
application.register("cross-stitch-fabric-calculator", CrossStitchFabricCalculatorController)
application.register("hvac-btu-calculator", HvacBtuCalculatorController)

// Alcohol & Brewing
application.register("abv-calculator", AbvCalculatorController)
application.register("ibu-calculator", IbuCalculatorController)
application.register("srm-calculator", SrmCalculatorController)
application.register("strike-water-calculator", StrikeWaterCalculatorController)
application.register("hydrometer-correction-calculator", HydrometerCorrectionCalculatorController)
application.register("brix-to-gravity-calculator", BrixToGravityCalculatorController)
application.register("yeast-pitch-calculator", YeastPitchCalculatorController)
application.register("priming-sugar-calculator", PrimingSugarCalculatorController)
application.register("keg-force-carbonation-calculator", KegForceCarbonationCalculatorController)
application.register("distiller-proofing-calculator", DistillerProofingCalculatorController)
application.register("cocktail-abv-calculator", CocktailAbvCalculatorController)
application.register("pour-cost-calculator", PourCostCalculatorController)

// Geography
application.register("coordinate-distance-calculator", CoordinateDistanceCalculatorController)
application.register("latitude-longitude-converter", LatitudeLongitudeConverterController)
application.register("bearing-calculator", BearingCalculatorController)
application.register("midpoint-calculator", MidpointCalculatorController)
application.register("map-scale-calculator", MapScaleCalculatorController)
application.register("population-density-calculator", PopulationDensityCalculatorController)
application.register("destination-point-calculator", DestinationPointCalculatorController)
application.register("antipode-calculator", AntipodeCalculatorController)
application.register("rhumb-line-calculator", RhumbLineCalculatorController)
application.register("polygon-area-calculator", PolygonAreaCalculatorController)
application.register("hiking-time-calculator", HikingTimeCalculatorController)
application.register("geohash-converter", GeohashConverterController)
application.register("degrees-to-kilometers-converter", DegreesToKilometersConverterController)
application.register("flight-time-calculator", FlightTimeCalculatorController)

// Gardening
application.register("mulch-calculator", MulchCalculatorController)
application.register("topsoil-calculator", TopsoilCalculatorController)
application.register("raised-bed-soil-calculator", RaisedBedSoilCalculatorController)
application.register("compost-calculator", CompostCalculatorController)
application.register("fertilizer-calculator", FertilizerCalculatorController)
application.register("grass-seed-calculator", GrassSeedCalculatorController)
application.register("lawn-watering-calculator", LawnWateringCalculatorController)
application.register("plant-spacing-calculator", PlantSpacingCalculatorController)
application.register("growing-degree-days-calculator", GrowingDegreeDaysCalculatorController)
application.register("tree-age-calculator", TreeAgeCalculatorController)
application.register("greenhouse-heater-calculator", GreenhouseHeaterCalculatorController)
application.register("compost-ratio-calculator", CompostRatioCalculatorController)

// Everyday
application.register("tip-calculator", TipCalculatorController)
application.register("discount-calculator", DiscountCalculatorController)
application.register("age-calculator", AgeCalculatorController)
application.register("date-difference-calculator", DateDifferenceCalculatorController)
application.register("gas-mileage-calculator", GasMileageCalculatorController)
application.register("fuel-cost-calculator", FuelCostCalculatorController)
application.register("gpa-calculator", GpaCalculatorController)
application.register("cooking-converter", CookingConverterController)
application.register("time-zone-converter-calculator", TimeZoneConverterCalculatorController)
application.register("shoe-size-calculator", ShoeSizeCalculatorController)
application.register("grade-calculator", GradeCalculatorController)
application.register("electricity-bill-calculator", ElectricityBillCalculatorController)
application.register("moving-cost-calculator", MovingCostCalculatorController)
application.register("password-strength-calculator", PasswordStrengthCalculatorController)
application.register("screen-size-calculator", ScreenSizeCalculatorController)
application.register("bandwidth-calculator", BandwidthCalculatorController)
application.register("unit-price-calculator", UnitPriceCalculatorController)
application.register("secure-random-calculator", SecureRandomCalculatorController)
application.register("uuid-generator-calculator", UuidGeneratorCalculatorController)
application.register("hash-generator-calculator", HashGeneratorCalculatorController)
application.register("hmac-generator-calculator", HmacGeneratorCalculatorController)
application.register("jwt-decoder-calculator", JwtDecoderCalculatorController)
application.register("sql-formatter-calculator", SqlFormatterCalculatorController)
application.register("cron-parser-calculator", CronParserCalculatorController)
application.register("cron-builder-calculator", CronBuilderCalculatorController)
application.register("color-converter-calculator", ColorConverterCalculatorController)
application.register("url-parser-calculator", UrlParserCalculatorController)
application.register("http-header-parser-calculator", HttpHeaderParserCalculatorController)
application.register("subnet-calculator", SubnetCalculatorController)
application.register("unix-timestamp-calculator", UnixTimestampCalculatorController)
application.register("yaml-to-json-calculator", YamlToJsonCalculatorController)
application.register("csv-to-json-calculator", CsvToJsonCalculatorController)
application.register("xml-to-json-calculator", XmlToJsonCalculatorController)
application.register("html-entity-encoder-calculator", HtmlEntityEncoderCalculatorController)
application.register("code-minifier-calculator", CodeMinifierCalculatorController)
application.register("escape-unescape-calculator", EscapeUnescapeCalculatorController)
application.register("csv-to-excel-calculator", CsvToExcelCalculatorController)
application.register("excel-to-csv-calculator", ExcelToCsvCalculatorController)
application.register("markdown-to-html-calculator", MarkdownToHtmlCalculatorController)
application.register("html-to-markdown-calculator", HtmlToMarkdownCalculatorController)
application.register("txt-to-pdf-calculator", TxtToPdfCalculatorController)
application.register("csv-to-pdf-calculator", CsvToPdfCalculatorController)
application.register("markdown-to-pdf-calculator", MarkdownToPdfCalculatorController)
application.register("excel-to-pdf-calculator", ExcelToPdfCalculatorController)
application.register("docx-to-pdf-calculator", DocxToPdfCalculatorController)
application.register("color-palette-picker-calculator", ColorPalettePickerCalculatorController)
application.register("password-generator-calculator", PasswordGeneratorCalculatorController)
application.register("csp-builder-calculator", CspBuilderCalculatorController)
application.register("chmod-calculator", ChmodCalculatorController)
application.register("port-reference-calculator", PortReferenceCalculatorController)
application.register("qr-code-generator-calculator", QrCodeGeneratorCalculatorController)
application.register("base64-image-encoder-calculator", Base64ImageEncoderCalculatorController)
application.register("markdown-table-generator-calculator", MarkdownTableGeneratorCalculatorController)
application.register("json-to-csv-calculator", JsonToCsvCalculatorController)
application.register("nginx-config-generator-calculator", NginxConfigGeneratorCalculatorController)
application.register("dockerfile-generator-calculator", DockerfileGeneratorCalculatorController)
application.register("gitignore-generator-calculator", GitignoreGeneratorCalculatorController)
application.register("env-validator-calculator", EnvValidatorCalculatorController)
application.register("regex-builder-calculator", RegexBuilderCalculatorController)
application.register("cors-checker-calculator", CorsCheckerCalculatorController)
application.register("ssl-cert-decoder-calculator", SslCertDecoderCalculatorController)
application.register("ip-lookup-calculator", IpLookupCalculatorController)
application.register("dns-lookup-calculator", DnsLookupCalculatorController)
application.register("mac-lookup-calculator", MacLookupCalculatorController)
application.register("odt-to-docx-calculator", OdtToDocxCalculatorController)
application.register("odt-to-pdf-calculator", OdtToPdfCalculatorController)
application.register("docx-to-odt-calculator", DocxToOdtCalculatorController)

application.register("alarm-timer-calculator", AlarmTimerCalculatorController)
application.register("alarm-clock-calculator", AlarmClockCalculatorController)
application.register("alarm-clock-active-calculator", AlarmClockActiveCalculatorController)
application.register("stopwatch-calculator", StopwatchCalculatorController)
application.register("pomodoro-timer-calculator", PomodoroTimerCalculatorController)
application.register("text-to-speech-calculator", TextToSpeechCalculatorController)

application.register("temperature-converter-calculator", TemperatureConverterCalculatorController)
application.register("length-converter-calculator", LengthConverterCalculatorController)
application.register("weight-converter-calculator", WeightConverterCalculatorController)
application.register("speed-converter-calculator", SpeedConverterCalculatorController)
application.register("byte-converter-calculator", ByteConverterCalculatorController)
application.register("cup-converter-calculator", CupConverterCalculatorController)
application.register("volume-converter-calculator", VolumeConverterCalculatorController)
application.register("calorie-tracker", CalorieTrackerController)
application.register("calorie-tracker-summary", CalorieTrackerSummaryController)

application.register("css-box-shadow-calculator", CssBoxShadowCalculatorController)
application.register("css-flexbox-calculator", CssFlexboxCalculatorController)
application.register("px-to-rem-calculator", PxToRemCalculatorController)
application.register("meta-tag-generator-calculator", MetaTagGeneratorCalculatorController)
application.register("favicon-generator-calculator", FaviconGeneratorCalculatorController)

application.register("schema-generator-calculator", SchemaGeneratorCalculatorController)
application.register("keyword-density-calculator", KeywordDensityCalculatorController)
application.register("prime-checker-calculator", PrimeCheckerCalculatorController)
application.register("random-number-calculator", RandomNumberCalculatorController)
application.register("image-resizer-calculator", ImageResizerCalculatorController)

application.register("morse-code-calculator", MorseCodeCalculatorController)
application.register("roman-numeral-calculator", RomanNumeralCalculatorController)
application.register("fake-data-generator-calculator", FakeDataGeneratorCalculatorController)
application.register("barcode-generator-calculator", BarcodeGeneratorCalculatorController)

// IT tools
application.register("http-status-reference-calculator", HttpStatusReferenceCalculatorController)
application.register("og-preview-calculator", OgPreviewCalculatorController)
application.register("curl-to-code-calculator", CurlToCodeCalculatorController)
application.register("json-to-yaml-calculator", JsonToYamlCalculatorController)
application.register("json-to-typescript-calculator", JsonToTypescriptCalculatorController)
application.register("html-formatter-calculator", HtmlFormatterCalculatorController)
application.register("css-formatter-calculator", CssFormatterCalculatorController)
application.register("js-formatter-calculator", JsFormatterCalculatorController)
application.register("html-to-jsx-calculator", HtmlToJsxCalculatorController)
application.register("robots-txt-calculator", RobotsTxtCalculatorController)
application.register("svg-to-png-calculator", SvgToPngCalculatorController)
application.register("base64-encoder-calculator", Base64EncoderCalculatorController)
application.register("url-encoder-calculator", UrlEncoderCalculatorController)
application.register("hex-ascii-calculator", HexAsciiCalculatorController)

// Suites
application.register("suite-stepper", SuiteStepperController)

// UI
application.register("dark-mode", DarkModeController)
application.register("navbar", NavbarController)
application.register("calculator-search", CalculatorSearchController)
application.register("cookie-consent", CookieConsentController)
application.register("ad-engagement", AdEngagementController)
application.register("calculator-rating", CalculatorRatingController)
application.register("chart", ChartController)
application.register("email-capture", EmailCaptureController)
application.register("track-visit", TrackVisitController)
application.register("recent-calculators", RecentCalculatorsController)
application.register("favorite", FavoriteController)
application.register("csv-export", CsvExportController)
application.register("calculation-history", CalculationHistoryController)
