require "test_helper"

class Everyday::GitignoreGeneratorCalculatorTest < ActiveSupport::TestCase
  test "generates Ruby gitignore" do
    result = Everyday::GitignoreGeneratorCalculator.new(templates: [ "ruby" ]).call
    assert_equal true, result[:valid]
    assert_includes result[:content], "/.bundle"
    assert_includes result[:content], "/vendor/bundle"
    assert_includes result[:content], ".env"
    assert_equal 1, result[:template_count]
    assert result[:line_count] > 0
  end

  test "generates Node gitignore" do
    result = Everyday::GitignoreGeneratorCalculator.new(templates: [ "node" ]).call
    assert_equal true, result[:valid]
    assert_includes result[:content], "node_modules/"
    assert_includes result[:content], "dist/"
  end

  test "generates Python gitignore" do
    result = Everyday::GitignoreGeneratorCalculator.new(templates: [ "python" ]).call
    assert_equal true, result[:valid]
    assert_includes result[:content], "__pycache__/"
    assert_includes result[:content], "venv/"
  end

  test "combines multiple templates" do
    result = Everyday::GitignoreGeneratorCalculator.new(templates: [ "ruby", "node", "macos" ]).call
    assert_equal true, result[:valid]
    assert_includes result[:content], "/.bundle"
    assert_includes result[:content], "node_modules/"
    assert_includes result[:content], ".DS_Store"
    assert_equal 3, result[:template_count]
    assert_equal [ "ruby", "node", "macos" ], result[:templates_used]
  end

  test "includes header with template names" do
    result = Everyday::GitignoreGeneratorCalculator.new(templates: [ "go", "jetbrains" ]).call
    assert_equal true, result[:valid]
    assert_includes result[:content], "# Generated by Calc Hammer"
    assert_includes result[:content], "go, jetbrains"
  end

  test "handles all supported templates" do
    Everyday::GitignoreGeneratorCalculator::TEMPLATE_NAMES.each do |template|
      result = Everyday::GitignoreGeneratorCalculator.new(templates: [ template ]).call
      assert_equal true, result[:valid], "Template '#{template}' should generate valid output"
      assert result[:content].present?, "Template '#{template}' should produce content"
    end
  end

  test "accepts comma-separated string" do
    result = Everyday::GitignoreGeneratorCalculator.new(templates: "ruby,node").call
    assert_equal true, result[:valid]
    assert_equal 2, result[:template_count]
  end

  test "ignores unknown templates" do
    result = Everyday::GitignoreGeneratorCalculator.new(templates: [ "ruby", "unknown_lang" ]).call
    assert_equal true, result[:valid]
    assert_equal 1, result[:template_count]
    assert_equal [ "ruby" ], result[:templates_used]
  end

  test "generates Go gitignore" do
    result = Everyday::GitignoreGeneratorCalculator.new(templates: [ "go" ]).call
    assert_equal true, result[:valid]
    assert_includes result[:content], "/vendor/"
    assert_includes result[:content], "*.exe"
  end

  test "generates macOS gitignore" do
    result = Everyday::GitignoreGeneratorCalculator.new(templates: [ "macos" ]).call
    assert_equal true, result[:valid]
    assert_includes result[:content], ".DS_Store"
  end

  test "generates Windows gitignore" do
    result = Everyday::GitignoreGeneratorCalculator.new(templates: [ "windows" ]).call
    assert_equal true, result[:valid]
    assert_includes result[:content], "Thumbs.db"
    assert_includes result[:content], "Desktop.ini"
  end

  test "generates VS Code gitignore" do
    result = Everyday::GitignoreGeneratorCalculator.new(templates: [ "vscode" ]).call
    assert_equal true, result[:valid]
    assert_includes result[:content], ".vscode/*"
  end

  # --- Validation errors ---

  test "error when no templates selected" do
    result = Everyday::GitignoreGeneratorCalculator.new(templates: []).call
    assert_equal false, result[:valid]
    assert_includes result[:errors], "At least one template must be selected"
  end

  test "error when all templates are unknown" do
    result = Everyday::GitignoreGeneratorCalculator.new(templates: [ "fantasy_lang" ]).call
    assert_equal false, result[:valid]
    assert_includes result[:errors], "At least one template must be selected"
  end

  test "errors accessor returns empty array before call" do
    calc = Everyday::GitignoreGeneratorCalculator.new(templates: [ "ruby" ])
    assert_equal [], calc.errors
  end
end
