namespace :everyday do
  get "tip-calculator", to: "calculators#tip", as: :tip
  get "discount-calculator", to: "calculators#discount", as: :discount
  get "age-calculator", to: "calculators#age", as: :age
  get "date-difference-calculator", to: "calculators#date_difference", as: :date_difference
  get "gas-mileage-calculator", to: "calculators#gas_mileage", as: :gas_mileage
  get "fuel-cost-calculator", to: "calculators#fuel_cost", as: :fuel_cost
  get "gpa-calculator", to: "calculators#gpa", as: :gpa
  get "cooking-converter", to: "calculators#cooking_converter", as: :cooking_converter
  get "time-zone-converter", to: "calculators#time_zone_converter", as: :time_zone_converter
  get "shoe-size-converter", to: "calculators#shoe_size", as: :shoe_size
  get "grade-calculator", to: "calculators#grade", as: :grade
  get "electricity-bill-calculator", to: "calculators#electricity_bill", as: :electricity_bill
  get "moving-cost-calculator", to: "calculators#moving_cost", as: :moving_cost
  get "password-strength-calculator", to: "calculators#password_strength", as: :password_strength
  get "screen-size-calculator", to: "calculators#screen_size", as: :screen_size
  get "bandwidth-calculator", to: "calculators#bandwidth", as: :bandwidth
  get "unit-price-calculator", to: "calculators#unit_price", as: :unit_price

  # Micro-calculator variants
  get "restaurant-tip-calculator", to: "calculators#restaurant_tip", as: :restaurant_tip
  get "delivery-tip-calculator", to: "calculators#delivery_tip", as: :delivery_tip
  get "hair-salon-tip-calculator", to: "calculators#hair_salon_tip", as: :hair_salon_tip
  get "bar-tip-calculator", to: "calculators#bar_tip", as: :bar_tip
  get "sale-price-calculator", to: "calculators#sale_price", as: :sale_price
  get "coupon-calculator", to: "calculators#coupon", as: :coupon
  get "clearance-calculator", to: "calculators#clearance", as: :clearance
  get "cost-per-km-calculator", to: "calculators#cost_per_km", as: :cost_per_km
  get "kwh-to-cost-calculator", to: "calculators#kwh_to_cost", as: :kwh_to_cost
  get "rent-per-sqm-calculator", to: "calculators#rent_per_sqm", as: :rent_per_sqm
  get "price-per-weight-calculator", to: "calculators#price_per_weight", as: :price_per_weight
  get "fuel-cost-trip-calculator", to: "calculators#fuel_cost_trip", as: :fuel_cost_trip
  get "data-usage-cost-calculator", to: "calculators#data_usage_cost", as: :data_usage_cost
  get "cost-per-person-calculator", to: "calculators#cost_per_person", as: :cost_per_person
  get "cost-per-day-calculator", to: "calculators#cost_per_day", as: :cost_per_day
  get "cost-per-hour-calculator", to: "calculators#cost_per_hour", as: :cost_per_hour
  get "cost-per-serving-calculator", to: "calculators#cost_per_serving", as: :cost_per_serving
  get "cost-per-wear-calculator", to: "calculators#cost_per_wear", as: :cost_per_wear
  get "cost-per-page-calculator", to: "calculators#cost_per_page", as: :cost_per_page
  get "price-per-liter-calculator", to: "calculators#price_per_liter", as: :price_per_liter
  get "words-per-minute-calculator", to: "calculators#words_per_minute", as: :words_per_minute
  get "cost-per-mile-calculator", to: "calculators#cost_per_mile", as: :cost_per_mile
  get "work-hours-calculator", to: "calculators#work_hours", as: :work_hours
  get "shift-duration-calculator", to: "calculators#shift_duration", as: :shift_duration
  get "days-until-calculator", to: "calculators#days_until", as: :days_until
  get "business-days-calculator", to: "calculators#business_days", as: :business_days
  get "time-card-calculator", to: "calculators#time_card", as: :time_card
  get "work-break-calculator", to: "calculators#work_break", as: :work_break
  get "word-counter", to: "calculators#word_counter", as: :word_counter
  get "character-counter", to: "calculators#character_counter", as: :character_counter
  get "case-converter", to: "calculators#case_converter", as: :case_converter
  get "remove-duplicates", to: "calculators#remove_duplicates", as: :remove_duplicates
  get "json-formatter", to: "calculators#json_formatter", as: :json_formatter
  get "lorem-ipsum-generator", to: "calculators#lorem_ipsum", as: :lorem_ipsum
  get "text-diff-checker", to: "calculators#text_diff", as: :text_diff
  get "string-encoder-decoder", to: "calculators#string_encoder", as: :string_encoder
  get "regex-tester", to: "calculators#regex_tester", as: :regex_tester
  get "markdown-preview", to: "calculators#markdown_preview", as: :markdown_preview
  get "secure-random-generator", to: "calculators#secure_random", as: :secure_random
  get "uuid-generator", to: "calculators#uuid_generator", as: :uuid_generator
  get "hash-generator", to: "calculators#hash_generator", as: :hash_generator
  get "hmac-generator", to: "calculators#hmac_generator", as: :hmac_generator
  get "code-minifier-beautifier", to: "calculators#code_minifier", as: :code_minifier
  get "escape-unescape-tool", to: "calculators#escape_unescape", as: :escape_unescape
  get "jwt-decoder", to: "calculators#jwt_decoder", as: :jwt_decoder
  get "sql-formatter", to: "calculators#sql_formatter", as: :sql_formatter
  get "cron-expression-parser", to: "calculators#cron_parser", as: :cron_parser
  get "yaml-to-json-converter", to: "calculators#yaml_to_json", as: :yaml_to_json
  get "csv-to-json-converter", to: "calculators#csv_to_json", as: :csv_to_json
  get "xml-to-json-converter", to: "calculators#xml_to_json", as: :xml_to_json
  get "url-parser", to: "calculators#url_parser", as: :url_parser
  get "http-header-parser", to: "calculators#http_header_parser", as: :http_header_parser
  get "cidr-subnet-calculator", to: "calculators#subnet_calculator", as: :subnet_calculator
  get "unix-timestamp-converter", to: "calculators#unix_timestamp", as: :unix_timestamp
  get "color-converter", to: "calculators#color_converter", as: :color_converter
  get "html-entity-encoder-decoder", to: "calculators#html_entity_encoder", as: :html_entity_encoder
  get "csv-to-excel-converter", to: "calculators#csv_to_excel", as: :csv_to_excel
  get "excel-to-csv-converter", to: "calculators#excel_to_csv", as: :excel_to_csv
  get "markdown-to-html-converter", to: "calculators#markdown_to_html", as: :markdown_to_html
  get "html-to-markdown-converter", to: "calculators#html_to_markdown", as: :html_to_markdown
  get "txt-to-pdf-converter", to: "calculators#txt_to_pdf", as: :txt_to_pdf
  get "csv-to-pdf-converter", to: "calculators#csv_to_pdf", as: :csv_to_pdf
  get "markdown-to-pdf-converter", to: "calculators#markdown_to_pdf", as: :markdown_to_pdf
  get "excel-to-pdf-converter", to: "calculators#excel_to_pdf", as: :excel_to_pdf
  get "docx-to-pdf-converter", to: "calculators#docx_to_pdf", as: :docx_to_pdf
  get "cron-job-generator", to: "calculators#cron_builder", as: :cron_builder
  get "color-palette-picker", to: "calculators#color_palette_picker", as: :color_palette_picker
  get "password-generator", to: "calculators#password_generator", as: :password_generator
  get "csp-header-builder", to: "calculators#csp_builder", as: :csp_builder
  get "chmod-calculator", to: "calculators#chmod_calculator", as: :chmod_calculator
  get "port-number-reference", to: "calculators#port_reference", as: :port_reference
  get "qr-code-generator", to: "calculators#qr_code_generator", as: :qr_code_generator
  get "base64-image-encoder", to: "calculators#base64_image_encoder", as: :base64_image_encoder
  get "markdown-table-generator", to: "calculators#markdown_table_generator", as: :markdown_table_generator
  get "json-to-csv-converter", to: "calculators#json_to_csv", as: :json_to_csv
  get "nginx-config-generator", to: "calculators#nginx_config_generator", as: :nginx_config_generator
  get "dockerfile-generator", to: "calculators#dockerfile_generator", as: :dockerfile_generator
  get "gitignore-generator", to: "calculators#gitignore_generator", as: :gitignore_generator
  get "env-variable-validator", to: "calculators#env_validator", as: :env_validator
  get "regex-builder", to: "calculators#regex_builder", as: :regex_builder
  get "cors-header-checker", to: "calculators#cors_checker", as: :cors_checker
  get "ssl-certificate-decoder", to: "calculators#ssl_cert_decoder", as: :ssl_cert_decoder
  get "ip-address-lookup", to: "calculators#ip_lookup", as: :ip_lookup
  get "dns-lookup", to: "calculators#dns_lookup", as: :dns_lookup
  get "mac-address-lookup", to: "calculators#mac_lookup", as: :mac_lookup
  get "odt-to-docx-converter", to: "calculators#odt_to_docx", as: :odt_to_docx
  get "odt-to-pdf-converter", to: "calculators#odt_to_pdf", as: :odt_to_pdf
  get "docx-to-odt-converter", to: "calculators#docx_to_odt", as: :docx_to_odt
  get "base64-encoder-decoder", to: "calculators#base64_encoder", as: :base64_encoder
  get "url-encoder-decoder", to: "calculators#url_encoder", as: :url_encoder
  get "html-formatter-beautifier", to: "calculators#html_formatter", as: :html_formatter
  get "css-formatter-beautifier", to: "calculators#css_formatter", as: :css_formatter
  get "javascript-formatter-beautifier", to: "calculators#js_formatter", as: :js_formatter
  get "json-validator", to: "calculators#json_validator", as: :json_validator
  get "json-to-yaml-converter", to: "calculators#json_to_yaml", as: :json_to_yaml
  get "curl-to-code-converter", to: "calculators#curl_to_code", as: :curl_to_code
  get "json-to-typescript-generator", to: "calculators#json_to_typescript", as: :json_to_typescript
  get "html-to-jsx-converter", to: "calculators#html_to_jsx", as: :html_to_jsx
  get "hex-ascii-converter", to: "calculators#hex_ascii", as: :hex_ascii
  get "http-status-code-reference", to: "calculators#http_status_reference", as: :http_status_reference
  get "robots-txt-generator", to: "calculators#robots_txt", as: :robots_txt
  get "htaccess-generator", to: "calculators#htaccess_generator", as: :htaccess_generator
  get "regex-explainer", to: "calculators#regex_explainer", as: :regex_explainer
  get "open-graph-preview", to: "calculators#og_preview", as: :og_preview
  get "svg-to-png-converter", to: "calculators#svg_to_png", as: :svg_to_png
  get "alarm-timer", to: "calculators#alarm_timer", as: :alarm_timer
  get "alarm-clock", to: "calculators#alarm_clock", as: :alarm_clock
  get "alarm-clock/active", to: "calculators#alarm_clock_active", as: :alarm_clock_active
  get "stopwatch", to: "calculators#stopwatch", as: :stopwatch
  get "pomodoro-timer", to: "calculators#pomodoro_timer", as: :pomodoro_timer
  get "text-to-speech", to: "calculators#text_to_speech", as: :text_to_speech
  get "temperature-converter", to: "calculators#temperature_converter", as: :temperature_converter
  get "length-converter", to: "calculators#length_converter", as: :length_converter
  get "weight-converter", to: "calculators#weight_converter", as: :weight_converter
  get "speed-converter", to: "calculators#speed_converter", as: :speed_converter
  get "byte-converter", to: "calculators#byte_converter", as: :byte_converter
  get "cup-converter", to: "calculators#cup_converter", as: :cup_converter
  get "teaspoon-converter", to: "calculators#teaspoon_converter", as: :teaspoon_converter
  get "tablespoon-converter", to: "calculators#tablespoon_converter", as: :tablespoon_converter
  get "volume-converter", to: "calculators#volume_converter", as: :volume_converter
  get "calorie-tracker", to: "calculators#calorie_tracker", as: :calorie_tracker
  get "calorie-tracker/history", to: "calculators#calorie_tracker_summary", as: :calorie_tracker_summary
  get "css-box-shadow-generator", to: "calculators#css_box_shadow", as: :css_box_shadow
  get "css-flexbox-generator", to: "calculators#css_flexbox", as: :css_flexbox
  get "px-to-rem-converter", to: "calculators#px_to_rem", as: :px_to_rem
  get "meta-tag-generator", to: "calculators#meta_tag_generator", as: :meta_tag_generator
  get "favicon-generator", to: "calculators#favicon_generator", as: :favicon_generator
  get "morse-code-translator", to: "calculators#morse_code", as: :morse_code
  get "roman-numeral-converter", to: "calculators#roman_numeral", as: :roman_numeral
  get "fake-data-generator", to: "calculators#fake_data_generator", as: :fake_data_generator
  get "barcode-generator", to: "calculators#barcode_generator", as: :barcode_generator
  get "schema-markup-generator", to: "calculators#schema_generator", as: :schema_generator
  get "keyword-density-checker", to: "calculators#keyword_density", as: :keyword_density
  get "prime-number-checker", to: "calculators#prime_checker", as: :prime_checker
  get "random-number-generator", to: "calculators#random_number", as: :random_number
  get "image-resizer", to: "calculators#image_resizer", as: :image_resizer
  get "split-bill-calculator", to: "calculators#split_bill", as: :split_bill
  get "wedding-budget-calculator", to: "calculators#wedding_budget", as: :wedding_budget
  get "travel-budget-calculator", to: "calculators#travel_budget", as: :travel_budget
  get "pet-cost-calculator", to: "calculators#pet_cost", as: :pet_cost
  get "electricity-usage-calculator", to: "calculators#electricity_usage", as: :electricity_usage
  get "subscription-cost-calculator", to: "calculators#subscription_cost", as: :subscription_cost
  get "jwt-generator", to: "calculators#jwt_generator_tool", as: :jwt_generator_tool
  get "api-response-time-calculator", to: "calculators#api_response_time", as: :api_response_time
  get "database-size-estimator", to: "calculators#database_size", as: :database_size
  get "text-encryptor", to: "calculators#text_encryptor", as: :text_encryptor
  get "uptime-calculator", to: "calculators#uptime_calculator", as: :uptime_calculator
  get "citation-generator", to: "calculators#citation_generator", as: :citation_generator
  get "plagiarism-calculator", to: "calculators#plagiarism", as: :plagiarism
  get "final-grade-calculator", to: "calculators#final_grade", as: :final_grade
  get "student-budget-calculator", to: "calculators#student_budget", as: :student_budget
  get "study-time-calculator", to: "calculators#study_time", as: :study_time
end
