namespace :finance do
  get "mortgage-calculator", to: "calculators#mortgage", as: :mortgage
  get "compound-interest-calculator", to: "calculators#compound_interest", as: :compound_interest
  get "loan-calculator", to: "calculators#loan", as: :loan
  get "investment-calculator", to: "calculators#investment", as: :investment
  get "retirement-calculator", to: "calculators#retirement", as: :retirement
  get "pension-calculator", to: "calculators#pension", as: :pension
  get "debt-payoff-calculator", to: "calculators#debt_payoff", as: :debt_payoff
  get "salary-calculator", to: "calculators#salary", as: :salary
  get "savings-goal-calculator", to: "calculators#savings_goal", as: :savings_goal
  get "roi-calculator", to: "calculators#roi", as: :roi
  get "profit-margin-calculator", to: "calculators#profit_margin", as: :profit_margin
  get "inflation-calculator", to: "calculators#inflation", as: :inflation
  get "break-even-calculator", to: "calculators#break_even", as: :break_even
  get "markup-margin-calculator", to: "calculators#markup_margin", as: :markup_margin
  get "rent-vs-buy-calculator", to: "calculators#rent_vs_buy", as: :rent_vs_buy
  get "dividend-yield-calculator", to: "calculators#dividend_yield", as: :dividend_yield
  get "dca-calculator", to: "calculators#dca", as: :dca
  get "solar-savings-calculator", to: "calculators#solar_savings", as: :solar_savings
  get "tax-bracket-calculator", to: "calculators#tax_bracket", as: :tax_bracket
  get "auto-loan-calculator", to: "calculators#auto_loan", as: :auto_loan
  get "credit-card-payoff-calculator", to: "calculators#credit_card_payoff", as: :credit_card_payoff
  get "net-worth-calculator", to: "calculators#net_worth", as: :net_worth
  get "home-affordability-calculator", to: "calculators#home_affordability", as: :home_affordability
  get "business-loan-calculator", to: "calculators#business_loan", as: :business_loan
  get "currency-converter", to: "calculators#currency_converter", as: :currency_converter
  get "paycheck-calculator", to: "calculators#paycheck", as: :paycheck
  get "401k-calculator", to: "calculators#four_oh_one_k", as: :four_oh_one_k
  get "amortization-calculator", to: "calculators#amortization", as: :amortization
  get "stock-profit-calculator", to: "calculators#stock_profit", as: :stock_profit
  get "cd-calculator", to: "calculators#cd", as: :cd
  get "savings-interest-calculator", to: "calculators#savings_interest", as: :savings_interest
  get "house-flip-calculator", to: "calculators#house_flip", as: :house_flip
  get "student-loan-calculator", to: "calculators#student_loan", as: :student_loan
  get "estate-tax-calculator", to: "calculators#estate_tax", as: :estate_tax
  get "crypto-profit-calculator", to: "calculators#crypto_profit", as: :crypto_profit

  # Micro-calculator variants
  get "car-loan-calculator", to: "calculators#car_loan", as: :car_loan
  get "motorcycle-loan-calculator", to: "calculators#motorcycle_loan", as: :motorcycle_loan
  get "boat-loan-calculator", to: "calculators#boat_loan", as: :boat_loan
  get "personal-loan-calculator", to: "calculators#personal_loan", as: :personal_loan
  get "home-equity-loan-calculator", to: "calculators#home_equity_loan", as: :home_equity_loan
  get "rv-loan-calculator", to: "calculators#rv_loan", as: :rv_loan
  get "fha-mortgage-calculator", to: "calculators#fha_mortgage", as: :fha_mortgage
  get "va-mortgage-calculator", to: "calculators#va_mortgage", as: :va_mortgage
  get "refinance-calculator", to: "calculators#refinance", as: :refinance
  get "jumbo-mortgage-calculator", to: "calculators#jumbo_mortgage", as: :jumbo_mortgage
  get "savings-growth-calculator", to: "calculators#savings_growth", as: :savings_growth
  get "money-market-calculator", to: "calculators#money_market", as: :money_market
  get "hourly-paycheck-calculator", to: "calculators#hourly_paycheck", as: :hourly_paycheck
  get "freelance-tax-calculator", to: "calculators#freelance_tax", as: :freelance_tax
  get "salary-converter", to: "calculators#salary_converter", as: :salary_converter
  get "cost-of-living-calculator", to: "calculators#cost_of_living", as: :cost_of_living
  get "hourly-to-project-calculator", to: "calculators#hourly_to_project", as: :hourly_to_project
  get "cost-per-click-calculator", to: "calculators#cost_per_click", as: :cost_per_click
  get "cost-per-lead-calculator", to: "calculators#cost_per_lead", as: :cost_per_lead
  get "cost-per-acquisition-calculator", to: "calculators#cost_per_acquisition", as: :cost_per_acquisition
  get "revenue-per-employee-calculator", to: "calculators#revenue_per_employee", as: :revenue_per_employee
  get "earnings-per-share-calculator", to: "calculators#earnings_per_share", as: :earnings_per_share
  get "savings-per-month-calculator", to: "calculators#savings_per_month", as: :savings_per_month
  get "overtime-calculator", to: "calculators#overtime", as: :overtime
  get "hourly-to-salary-calculator", to: "calculators#hourly_to_salary", as: :hourly_to_salary
  get "invoice-generator", to: "calculators#invoice_generator", as: :invoice_generator
  get "detailed-invoice-generator", to: "calculators#detailed_invoice_generator", as: :detailed_invoice_generator
  get "fire-calculator", to: "calculators#fire", as: :fire
  get "rent-affordability-calculator", to: "calculators#rent_affordability", as: :rent_affordability
  get "capital-gains-tax-calculator", to: "calculators#capital_gains_tax", as: :capital_gains_tax
  get "down-payment-calculator", to: "calculators#down_payment", as: :down_payment
  get "inheritance-tax-calculator", to: "calculators#inheritance_tax", as: :inheritance_tax
  get "side-hustle-calculator", to: "calculators#side_hustle", as: :side_hustle
  get "emergency-fund-calculator", to: "calculators#emergency_fund", as: :emergency_fund
  get "lease-vs-buy-calculator", to: "calculators#lease_vs_buy", as: :lease_vs_buy
  get "heloc-calculator", to: "calculators#heloc", as: :heloc
  get "debt-snowball-vs-avalanche-calculator", to: "calculators#debt_snowball_avalanche", as: :debt_snowball_avalanche
  get "bond-yield-calculator", to: "calculators#bond_yield", as: :bond_yield
  get "options-profit-calculator", to: "calculators#options_profit", as: :options_profit
  get "freelance-rate-calculator", to: "calculators#freelance_rate", as: :freelance_rate
  get "sales-tax-calculator", to: "calculators#sales_tax", as: :sales_tax
  get "vat-calculator", to: "calculators#vat", as: :vat
  get "tip-pooling-calculator", to: "calculators#tip_pooling", as: :tip_pooling
  get "net-pay-calculator", to: "calculators#net_pay", as: :net_pay
  get "startup-runway-calculator", to: "calculators#startup_runway", as: :startup_runway
  get "saas-metrics-calculator", to: "calculators#saas_metrics", as: :saas_metrics
end
