# frozen_string_literal: true

module Physics
  module ElementData
    # Density in g/cm³ at standard conditions (20°C, 1 atm).
    # Gases use density at STP. Estimated values marked with comments.
    # Sources: IUPAC, CRC Handbook of Chemistry and Physics, NIST.
    ELEMENTS = [
      { z:   1, symbol: "H",  name: "Hydrogen",      density: 0.00008988, state: "gas" },
      { z:   2, symbol: "He", name: "Helium",         density: 0.0001785,  state: "gas" },
      { z:   3, symbol: "Li", name: "Lithium",        density: 0.534,      state: "solid" },
      { z:   4, symbol: "Be", name: "Beryllium",      density: 1.85,       state: "solid" },
      { z:   5, symbol: "B",  name: "Boron",          density: 2.34,       state: "solid" },
      { z:   6, symbol: "C",  name: "Carbon",         density: 2.267,      state: "solid" },
      { z:   7, symbol: "N",  name: "Nitrogen",       density: 0.0012506,  state: "gas" },
      { z:   8, symbol: "O",  name: "Oxygen",         density: 0.001429,   state: "gas" },
      { z:   9, symbol: "F",  name: "Fluorine",       density: 0.001696,   state: "gas" },
      { z:  10, symbol: "Ne", name: "Neon",           density: 0.0008999,  state: "gas" },
      { z:  11, symbol: "Na", name: "Sodium",         density: 0.971,      state: "solid" },
      { z:  12, symbol: "Mg", name: "Magnesium",      density: 1.738,      state: "solid" },
      { z:  13, symbol: "Al", name: "Aluminium",      density: 2.699,      state: "solid" },
      { z:  14, symbol: "Si", name: "Silicon",        density: 2.3296,     state: "solid" },
      { z:  15, symbol: "P",  name: "Phosphorus",     density: 1.82,       state: "solid" },
      { z:  16, symbol: "S",  name: "Sulfur",         density: 2.067,      state: "solid" },
      { z:  17, symbol: "Cl", name: "Chlorine",       density: 0.003214,   state: "gas" },
      { z:  18, symbol: "Ar", name: "Argon",          density: 0.001784,   state: "gas" },
      { z:  19, symbol: "K",  name: "Potassium",      density: 0.862,      state: "solid" },
      { z:  20, symbol: "Ca", name: "Calcium",        density: 1.55,       state: "solid" },
      { z:  21, symbol: "Sc", name: "Scandium",       density: 2.989,      state: "solid" },
      { z:  22, symbol: "Ti", name: "Titanium",       density: 4.506,      state: "solid" },
      { z:  23, symbol: "V",  name: "Vanadium",       density: 6.11,       state: "solid" },
      { z:  24, symbol: "Cr", name: "Chromium",       density: 7.15,       state: "solid" },
      { z:  25, symbol: "Mn", name: "Manganese",      density: 7.44,       state: "solid" },
      { z:  26, symbol: "Fe", name: "Iron",           density: 7.874,      state: "solid" },
      { z:  27, symbol: "Co", name: "Cobalt",         density: 8.90,       state: "solid" },
      { z:  28, symbol: "Ni", name: "Nickel",         density: 8.908,      state: "solid" },
      { z:  29, symbol: "Cu", name: "Copper",         density: 8.96,       state: "solid" },
      { z:  30, symbol: "Zn", name: "Zinc",           density: 7.134,      state: "solid" },
      { z:  31, symbol: "Ga", name: "Gallium",        density: 5.907,      state: "solid" },
      { z:  32, symbol: "Ge", name: "Germanium",      density: 5.323,      state: "solid" },
      { z:  33, symbol: "As", name: "Arsenic",        density: 5.776,      state: "solid" },
      { z:  34, symbol: "Se", name: "Selenium",       density: 4.809,      state: "solid" },
      { z:  35, symbol: "Br", name: "Bromine",        density: 3.122,      state: "liquid" },
      { z:  36, symbol: "Kr", name: "Krypton",        density: 0.003733,   state: "gas" },
      { z:  37, symbol: "Rb", name: "Rubidium",       density: 1.532,      state: "solid" },
      { z:  38, symbol: "Sr", name: "Strontium",      density: 2.64,       state: "solid" },
      { z:  39, symbol: "Y",  name: "Yttrium",        density: 4.469,      state: "solid" },
      { z:  40, symbol: "Zr", name: "Zirconium",      density: 6.506,      state: "solid" },
      { z:  41, symbol: "Nb", name: "Niobium",        density: 8.57,       state: "solid" },
      { z:  42, symbol: "Mo", name: "Molybdenum",     density: 10.22,      state: "solid" },
      { z:  43, symbol: "Tc", name: "Technetium",     density: 11.5,       state: "solid" },
      { z:  44, symbol: "Ru", name: "Ruthenium",      density: 12.37,      state: "solid" },
      { z:  45, symbol: "Rh", name: "Rhodium",        density: 12.41,      state: "solid" },
      { z:  46, symbol: "Pd", name: "Palladium",      density: 12.023,     state: "solid" },
      { z:  47, symbol: "Ag", name: "Silver",         density: 10.501,     state: "solid" },
      { z:  48, symbol: "Cd", name: "Cadmium",        density: 8.69,       state: "solid" },
      { z:  49, symbol: "In", name: "Indium",         density: 7.31,       state: "solid" },
      { z:  50, symbol: "Sn", name: "Tin",            density: 7.287,      state: "solid" },
      { z:  51, symbol: "Sb", name: "Antimony",       density: 6.685,      state: "solid" },
      { z:  52, symbol: "Te", name: "Tellurium",      density: 6.232,      state: "solid" },
      { z:  53, symbol: "I",  name: "Iodine",         density: 4.93,       state: "solid" },
      { z:  54, symbol: "Xe", name: "Xenon",          density: 0.005887,   state: "gas" },
      { z:  55, symbol: "Cs", name: "Caesium",        density: 1.873,      state: "solid" },
      { z:  56, symbol: "Ba", name: "Barium",         density: 3.594,      state: "solid" },
      { z:  57, symbol: "La", name: "Lanthanum",      density: 6.145,      state: "solid" },
      { z:  58, symbol: "Ce", name: "Cerium",         density: 6.77,       state: "solid" },
      { z:  59, symbol: "Pr", name: "Praseodymium",   density: 6.773,      state: "solid" },
      { z:  60, symbol: "Nd", name: "Neodymium",      density: 7.007,      state: "solid" },
      { z:  61, symbol: "Pm", name: "Promethium",     density: 7.26,       state: "solid" },
      { z:  62, symbol: "Sm", name: "Samarium",       density: 7.52,       state: "solid" },
      { z:  63, symbol: "Eu", name: "Europium",       density: 5.243,      state: "solid" },
      { z:  64, symbol: "Gd", name: "Gadolinium",     density: 7.895,      state: "solid" },
      { z:  65, symbol: "Tb", name: "Terbium",        density: 8.229,      state: "solid" },
      { z:  66, symbol: "Dy", name: "Dysprosium",     density: 8.55,       state: "solid" },
      { z:  67, symbol: "Ho", name: "Holmium",        density: 8.795,      state: "solid" },
      { z:  68, symbol: "Er", name: "Erbium",         density: 9.066,      state: "solid" },
      { z:  69, symbol: "Tm", name: "Thulium",        density: 9.321,      state: "solid" },
      { z:  70, symbol: "Yb", name: "Ytterbium",      density: 6.965,      state: "solid" },
      { z:  71, symbol: "Lu", name: "Lutetium",       density: 9.84,       state: "solid" },
      { z:  72, symbol: "Hf", name: "Hafnium",        density: 13.31,      state: "solid" },
      { z:  73, symbol: "Ta", name: "Tantalum",       density: 16.654,     state: "solid" },
      { z:  74, symbol: "W",  name: "Tungsten",       density: 19.25,      state: "solid" },
      { z:  75, symbol: "Re", name: "Rhenium",        density: 21.02,      state: "solid" },
      { z:  76, symbol: "Os", name: "Osmium",         density: 22.587,     state: "solid" },
      { z:  77, symbol: "Ir", name: "Iridium",        density: 22.56,      state: "solid" },
      { z:  78, symbol: "Pt", name: "Platinum",       density: 21.46,      state: "solid" },
      { z:  79, symbol: "Au", name: "Gold",           density: 19.282,     state: "solid" },
      { z:  80, symbol: "Hg", name: "Mercury",        density: 13.534,     state: "liquid" },
      { z:  81, symbol: "Tl", name: "Thallium",       density: 11.85,      state: "solid" },
      { z:  82, symbol: "Pb", name: "Lead",           density: 11.342,     state: "solid" },
      { z:  83, symbol: "Bi", name: "Bismuth",        density: 9.807,      state: "solid" },
      { z:  84, symbol: "Po", name: "Polonium",       density: 9.32,       state: "solid" },
      { z:  85, symbol: "At", name: "Astatine",       density: 6.35,       state: "solid" },
      { z:  86, symbol: "Rn", name: "Radon",          density: 0.00973,    state: "gas" },
      { z:  87, symbol: "Fr", name: "Francium",       density: 2.48,       state: "solid" },
      { z:  88, symbol: "Ra", name: "Radium",         density: 5.5,        state: "solid" },
      { z:  89, symbol: "Ac", name: "Actinium",       density: 10.07,      state: "solid" },
      { z:  90, symbol: "Th", name: "Thorium",        density: 11.72,      state: "solid" },
      { z:  91, symbol: "Pa", name: "Protactinium",   density: 15.37,      state: "solid" },
      { z:  92, symbol: "U",  name: "Uranium",        density: 18.95,      state: "solid" },
      { z:  93, symbol: "Np", name: "Neptunium",      density: 20.45,      state: "solid" },
      { z:  94, symbol: "Pu", name: "Plutonium",      density: 19.84,      state: "solid" },
      { z:  95, symbol: "Am", name: "Americium",      density: 13.69,      state: "solid" },
      { z:  96, symbol: "Cm", name: "Curium",         density: 13.51,      state: "solid" },
      { z:  97, symbol: "Bk", name: "Berkelium",      density: 14.79,      state: "solid" },
      { z:  98, symbol: "Cf", name: "Californium",    density: 15.1,       state: "solid" },
      { z:  99, symbol: "Es", name: "Einsteinium",    density: 8.84,       state: "solid" },
      { z: 100, symbol: "Fm", name: "Fermium",        density: nil,        state: "solid" },
      { z: 101, symbol: "Md", name: "Mendelevium",    density: nil,        state: "solid" },
      { z: 102, symbol: "No", name: "Nobelium",       density: nil,        state: "solid" },
      { z: 103, symbol: "Lr", name: "Lawrencium",     density: nil,        state: "solid" },
      { z: 104, symbol: "Rf", name: "Rutherfordium",  density: nil,        state: "solid" },
      { z: 105, symbol: "Db", name: "Dubnium",        density: nil,        state: "solid" },
      { z: 106, symbol: "Sg", name: "Seaborgium",     density: nil,        state: "solid" },
      { z: 107, symbol: "Bh", name: "Bohrium",        density: nil,        state: "solid" },
      { z: 108, symbol: "Hs", name: "Hassium",        density: nil,        state: "solid" },
      { z: 109, symbol: "Mt", name: "Meitnerium",     density: nil,        state: "solid" },
      { z: 110, symbol: "Ds", name: "Darmstadtium",   density: nil,        state: "solid" },
      { z: 111, symbol: "Rg", name: "Roentgenium",    density: nil,        state: "solid" },
      { z: 112, symbol: "Cn", name: "Copernicium",    density: nil,        state: "liquid" },
      { z: 113, symbol: "Nh", name: "Nihonium",       density: nil,        state: "solid" },
      { z: 114, symbol: "Fl", name: "Flerovium",      density: nil,        state: "solid" },
      { z: 115, symbol: "Mc", name: "Moscovium",      density: nil,        state: "solid" },
      { z: 116, symbol: "Lv", name: "Livermorium",    density: nil,        state: "solid" },
      { z: 117, symbol: "Ts", name: "Tennessine",     density: nil,        state: "solid" },
      { z: 118, symbol: "Og", name: "Oganesson",      density: nil,        state: "gas" }
    ].freeze

    # Only elements with known/measured densities are usable for calculations
    CALCULABLE_ELEMENTS = ELEMENTS.select { |e| e[:density] }.freeze

    def self.find_by_symbol(symbol)
      ELEMENTS.find { |e| e[:symbol] == symbol }
    end

    def self.density_for(symbol)
      find_by_symbol(symbol)&.dig(:density)
    end
  end
end
