module Everyday
  class CalculatorsController < ApplicationController
    def tip; end
    def discount; end
    def age; end
    def date_difference; end
    def gas_mileage; end
    def fuel_cost; end
    def gpa; end
    def cooking_converter; end
    def time_zone_converter; end
    def shoe_size; end
    def grade; end
    def electricity_bill; end
    def moving_cost; end
    def password_strength; end
    def screen_size; end
    def bandwidth; end
    def unit_price; end
    def restaurant_tip; end
    def delivery_tip; end
    def hair_salon_tip; end
    def bar_tip; end
    def sale_price; end
    def coupon; end
    def clearance; end
    def cost_per_km; end
    def kwh_to_cost; end
    def rent_per_sqm; end
    def price_per_weight; end
    def fuel_cost_trip; end
    def data_usage_cost; end
    def cost_per_person; end
    def cost_per_day; end
    def cost_per_hour; end
    def cost_per_serving; end
    def cost_per_wear; end
    def cost_per_page; end
    def price_per_liter; end
    def words_per_minute; end
    def cost_per_mile; end
    def work_hours; end
    def shift_duration; end
    def days_until; end
    def business_days; end
    def time_card; end
    def work_break; end
    def word_counter; end
    def character_counter; end
    def case_converter; end
    def remove_duplicates; end
    def json_formatter; end
    def lorem_ipsum; end
    def text_diff; end
    def string_encoder; end
    def regex_tester; end
    def markdown_preview; end

  end
end
