# frozen_string_literal: true

class CalculatorRegistry
  module CrossLinks
    CONSTRUCTION = {
      "concrete-calculator" => %w[gravel-mulch-calculator concrete-mix-calculator rebar-spacing-calculator],
      "paint-calculator" => %w[wallpaper-calculator flooring-calculator area-calculator],
      "flooring-calculator" => %w[area-calculator tile-calculator carpet-calculator],
      "tile-calculator" => %w[grout-calculator flooring-calculator area-calculator],
      "deck-calculator" => %w[lumber-calculator fence-calculator concrete-calculator],
      "fence-calculator" => %w[deck-calculator lumber-calculator gravel-mulch-calculator],
      "roofing-calculator" => %w[rafter-length-calculator roof-pitch-calculator attic-ventilation-calculator],
      "staircase-calculator" => %w[wheelchair-ramp-calculator rafter-length-calculator deck-calculator],
      "wallpaper-calculator" => %w[paint-calculator area-calculator flooring-calculator],
      "lumber-calculator" => %w[board-foot-calculator plywood-sheets-calculator wood-weight-calculator],
      "hvac-btu-calculator" => %w[cooling-load-calculator heat-loss-calculator heat-pump-capacity-calculator],
      "drywall-calculator" => %w[drywall-screws-calculator insulation-calculator paint-calculator],
      "insulation-calculator" => %w[heat-loss-calculator window-u-value-calculator drywall-calculator],
      "plumbing-calculator" => %w[pipe-friction-loss-calculator water-heater-sizing-calculator septic-tank-size-calculator],
      "electrical-load-calculator" => %w[wire-ampacity-calculator voltage-drop-calculator generator-sizing-calculator],
      "retaining-wall-calculator" => %w[gravel-mulch-calculator concrete-calculator paver-calculator],
      "miter-angle-calculator" => %w[rafter-length-calculator crown-molding-calculator cabinet-door-calculator],
      "wood-moisture-calculator" => %w[wood-shrinkage-calculator wood-weight-calculator board-foot-calculator],
      "wood-shrinkage-calculator" => %w[wood-moisture-calculator wood-weight-calculator lumber-calculator],
      "wood-weight-calculator" => %w[board-foot-calculator lumber-calculator wood-shrinkage-calculator],
      "rip-cut-calculator" => %w[board-foot-calculator lumber-calculator plywood-sheets-calculator],
      "cabinet-door-calculator" => %w[miter-angle-calculator wood-weight-calculator crown-molding-calculator],
      "grout-calculator" => %w[tile-calculator caulk-calculator paint-calculator],
      "carpet-calculator" => %w[flooring-calculator area-calculator paint-calculator],
      "baseboard-calculator" => %w[crown-molding-calculator caulk-calculator paint-calculator],
      "siding-calculator" => %w[area-calculator paint-calculator insulation-calculator],
      "gutter-calculator" => %w[roofing-calculator roof-pitch-calculator drainage-slope-calculator],
      "water-heater-sizing-calculator" => %w[plumbing-calculator pipe-friction-loss-calculator heat-loss-calculator],
      "pool-volume-calculator" => %w[buoyancy-calculator volume-converter hvac-btu-calculator],
      "kitchen-remodel-cost-calculator" => %w[bathroom-remodel-cost-calculator cabinet-door-calculator flooring-calculator],
      "bathroom-remodel-cost-calculator" => %w[kitchen-remodel-cost-calculator plumbing-calculator tile-calculator],
      "attic-ventilation-calculator" => %w[insulation-calculator heat-loss-calculator erv-hrv-ventilation-calculator],
      "solar-panel-layout-calculator" => %w[solar-savings-calculator solar-inverter-sizing-calculator electricity-cost-calculator],
      "rebar-spacing-calculator" => %w[concrete-mix-calculator concrete-calculator beam-load-span-calculator],
      "concrete-mix-calculator" => %w[concrete-calculator rebar-spacing-calculator spread-footing-calculator],
      "beam-load-span-calculator" => %w[joist-calculator rafter-length-calculator lumber-calculator],
      "window-u-value-calculator" => %w[insulation-calculator heat-loss-calculator heating-cost-calculator],
      "drainage-slope-calculator" => %w[gutter-calculator pipe-friction-loss-calculator excavation-calculator],
      "brick-block-calculator" => %w[paver-calculator retaining-wall-calculator concrete-calculator],
      "septic-tank-size-calculator" => %w[water-heater-sizing-calculator plumbing-calculator pool-volume-calculator],
      "asphalt-calculator" => %w[concrete-calculator gravel-mulch-calculator paver-calculator],
      "excavation-calculator" => %w[concrete-calculator gravel-mulch-calculator drainage-slope-calculator],
      "paver-calculator" => %w[concrete-calculator gravel-mulch-calculator retaining-wall-calculator],
      "board-foot-calculator" => %w[lumber-calculator wood-weight-calculator rip-cut-calculator],
      "rafter-length-calculator" => %w[roof-pitch-calculator roofing-calculator lumber-calculator],
      "roof-pitch-calculator" => %w[rafter-length-calculator roofing-calculator attic-ventilation-calculator],
      "stud-count-calculator" => %w[drywall-calculator lumber-calculator plywood-sheets-calculator],
      "plywood-sheets-calculator" => %w[stud-count-calculator lumber-calculator joist-calculator],
      "joist-calculator" => %w[beam-load-span-calculator plywood-sheets-calculator lumber-calculator],
      "voltage-drop-calculator" => %w[electrical-load-calculator wire-ampacity-calculator wire-gauge-calculator],
      "conduit-fill-calculator" => %w[wire-ampacity-calculator voltage-drop-calculator electrical-load-calculator],
      "pipe-friction-loss-calculator" => %w[plumbing-calculator water-heater-sizing-calculator pool-volume-calculator],
      "heat-loss-calculator" => %w[insulation-calculator window-u-value-calculator heating-cost-calculator],
      "duct-size-calculator" => %w[static-pressure-calculator hvac-btu-calculator air-change-rate-calculator],
      "spread-footing-calculator" => %w[concrete-mix-calculator rebar-spacing-calculator beam-load-span-calculator],
      "caulk-calculator" => %w[grout-calculator paint-calculator baseboard-calculator],
      "crown-molding-calculator" => %w[baseboard-calculator miter-angle-calculator paint-calculator],
      "chimney-flue-calculator" => %w[heat-loss-calculator hvac-btu-calculator heating-cost-calculator],
      "cooling-load-calculator" => %w[heat-loss-calculator hvac-btu-calculator insulation-calculator],
      "heat-pump-capacity-calculator" => %w[seer-eer-hspf-calculator cooling-load-calculator heat-loss-calculator],
      "seer-eer-hspf-calculator" => %w[heat-pump-capacity-calculator hvac-btu-calculator electricity-cost-calculator],
      "dehumidifier-sizing-calculator" => %w[psychrometric-calculator air-change-rate-calculator hvac-btu-calculator],
      "psychrometric-calculator" => %w[dehumidifier-sizing-calculator air-change-rate-calculator temperature-converter],
      "air-change-rate-calculator" => %w[erv-hrv-ventilation-calculator duct-size-calculator dehumidifier-sizing-calculator],
      "erv-hrv-ventilation-calculator" => %w[air-change-rate-calculator cooling-load-calculator heat-loss-calculator],
      "radiator-btu-calculator" => %w[heat-loss-calculator radiant-floor-heat-calculator heating-cost-calculator],
      "heating-cost-calculator" => %w[heat-loss-calculator electricity-bill-calculator solar-savings-calculator],
      "static-pressure-calculator" => %w[duct-size-calculator hvac-btu-calculator air-change-rate-calculator],
      "generator-sizing-calculator" => %w[electrical-load-calculator battery-backup-runtime-calculator wire-ampacity-calculator],
      "wire-ampacity-calculator" => %w[voltage-drop-calculator conduit-fill-calculator electrical-load-calculator],
      "radiant-floor-heat-calculator" => %w[heat-loss-calculator radiator-btu-calculator heating-cost-calculator],
      "drywall-screws-calculator" => %w[drywall-calculator stud-count-calculator plywood-sheets-calculator],
      "snow-melt-btu-calculator" => %w[heat-loss-calculator heating-cost-calculator hvac-btu-calculator],
      "solar-inverter-sizing-calculator" => %w[solar-panel-layout-calculator battery-backup-runtime-calculator solar-savings-calculator],
      "battery-backup-runtime-calculator" => %w[generator-sizing-calculator solar-inverter-sizing-calculator electricity-bill-calculator],
      # Construction gap-fills
      "gravel-mulch-calculator" => %w[concrete-calculator topsoil-calculator mulch-calculator],
      "price-per-sqm-calculator" => %w[sqft-cost-calculator flooring-calculator carpet-calculator],
      "sqft-cost-calculator" => %w[price-per-sqm-calculator flooring-calculator paint-calculator]
    }.freeze
  end
end
