# frozen_string_literal: true

class CalculatorRegistry
  module CrossLinks
    EVERYDAY = {
      "tip-calculator" => %w[discount-calculator percentage-calculator restaurant-tip-calculator],
      "discount-calculator" => %w[percentage-off-calculator sale-price-calculator coupon-calculator],
      "fuel-cost-calculator" => %w[gas-mileage-calculator mpg-calculator auto-loan-calculator],
      "gas-mileage-calculator" => %w[fuel-cost-calculator mpg-calculator ev-vs-gas-comparison-calculator],
      "cooking-converter" => %w[cup-converter weight-converter recipe-scaler],
      "cup-converter" => %w[cooking-converter teaspoon-converter volume-converter],
      "teaspoon-converter" => %w[tablespoon-converter cup-converter cooking-converter],
      "tablespoon-converter" => %w[teaspoon-converter cup-converter cooking-converter],
      "length-converter" => %w[area-calculator speed-converter weight-converter],
      "weight-converter" => %w[length-converter cooking-converter bmi-calculator],
      "temperature-converter" => %w[speed-converter length-converter weight-converter],
      "speed-converter" => %w[velocity-calculator length-converter pace-calculator],
      "volume-converter" => %w[cup-converter length-converter area-calculator],
      "byte-converter" => %w[bandwidth-calculator database-size-estimator data-usage-cost-calculator],
      "age-calculator" => %w[date-difference-calculator dog-age-calculator anniversary-calculator],
      "date-difference-calculator" => %w[age-calculator time-zone-converter business-days-calculator],
      "gpa-calculator" => %w[grade-calculator final-grade-calculator percentage-calculator],
      "grade-calculator" => %w[gpa-calculator final-grade-calculator percentage-calculator],
      "final-grade-calculator" => %w[grade-calculator gpa-calculator percentage-calculator],
      "electricity-bill-calculator" => %w[electricity-cost-calculator kwh-to-cost-calculator solar-savings-calculator],
      "electricity-usage-calculator" => %w[electricity-bill-calculator electricity-cost-calculator kwh-to-cost-calculator],
      "kwh-to-cost-calculator" => %w[electricity-cost-calculator electricity-bill-calculator electricity-usage-calculator],
      "work-hours-calculator" => %w[time-card-calculator shift-duration-calculator overtime-calculator],
      "time-card-calculator" => %w[work-hours-calculator shift-duration-calculator hourly-paycheck-calculator],
      "shift-duration-calculator" => %w[work-hours-calculator time-card-calculator overtime-calculator],
      "work-break-calculator" => %w[work-hours-calculator time-card-calculator shift-duration-calculator],
      "time-zone-converter" => %w[timezone-meeting-planner date-difference-calculator age-calculator],
      "timezone-meeting-planner" => %w[time-zone-converter date-difference-calculator work-hours-calculator],
      "shoe-size-converter" => %w[length-converter weight-converter cooking-converter],
      "moving-cost-calculator" => %w[fuel-cost-calculator rent-affordability-calculator rent-per-sqm-calculator],
      "password-strength-calculator" => %w[password-generator hash-generator secure-random-generator],
      "screen-size-calculator" => %w[aspect-ratio-calculator length-converter video-file-size-calculator],
      "bandwidth-calculator" => %w[byte-converter data-usage-cost-calculator api-response-time-calculator],
      "unit-price-calculator" => %w[price-per-weight-calculator price-per-liter-calculator cost-per-serving-calculator],
      "words-per-minute-calculator" => %w[word-counter character-counter research-paper-word-count-estimator],
      "business-days-calculator" => %w[date-difference-calculator age-calculator days-until-calculator],
      "days-until-calculator" => %w[date-difference-calculator age-calculator anniversary-calculator],
      "subscription-cost-calculator" => %w[cost-per-day-calculator cost-per-hour-calculator cost-per-wear-calculator],
      "carbon-footprint-calculator" => %w[electricity-bill-calculator fuel-cost-calculator mpg-calculator],
      "calorie-tracker" => %w[calorie-calculator macro-calculator tdee-calculator],
      "split-bill-calculator" => %w[tip-calculator restaurant-tip-calculator bar-tip-calculator],
      "travel-budget-calculator" => %w[moving-cost-calculator fuel-cost-calculator flight-time-calculator],
      "pet-cost-calculator" => %w[cat-food-calculator dog-food-calculator pet-insurance-roi-calculator],
      "restaurant-tip-calculator" => %w[tip-calculator bar-tip-calculator hair-salon-tip-calculator],
      "bar-tip-calculator" => %w[restaurant-tip-calculator tip-calculator hair-salon-tip-calculator],
      "delivery-tip-calculator" => %w[restaurant-tip-calculator tip-calculator hair-salon-tip-calculator],
      "hair-salon-tip-calculator" => %w[tip-calculator restaurant-tip-calculator bar-tip-calculator],
      "cost-per-day-calculator" => %w[cost-per-hour-calculator subscription-cost-calculator cost-per-wear-calculator],
      "cost-per-hour-calculator" => %w[cost-per-day-calculator hourly-paycheck-calculator subscription-cost-calculator],
      "cost-per-km-calculator" => %w[cost-per-mile-calculator fuel-cost-calculator mpg-calculator],
      "cost-per-mile-calculator" => %w[cost-per-km-calculator fuel-cost-calculator mpg-calculator],
      "cost-per-page-calculator" => %w[cost-per-serving-calculator print-size-dpi-calculator unit-price-calculator],
      "cost-per-person-calculator" => %w[cost-per-serving-calculator split-bill-calculator wedding-cost-splitter],
      "cost-per-serving-calculator" => %w[cost-per-person-calculator unit-price-calculator price-per-weight-calculator],
      "cost-per-wear-calculator" => %w[cost-per-day-calculator subscription-cost-calculator unit-price-calculator],
      "coupon-calculator" => %w[discount-calculator percentage-off-calculator sale-price-calculator],
      "clearance-calculator" => %w[discount-calculator percentage-off-calculator sale-price-calculator],
      "sale-price-calculator" => %w[discount-calculator percentage-off-calculator coupon-calculator],
      "price-per-liter-calculator" => %w[unit-price-calculator price-per-weight-calculator cost-per-serving-calculator],
      "price-per-weight-calculator" => %w[unit-price-calculator price-per-liter-calculator cost-per-serving-calculator],
      "rent-per-sqm-calculator" => %w[rent-affordability-calculator rent-vs-buy-calculator home-affordability-calculator],
      "fuel-cost-trip-calculator" => %w[fuel-cost-calculator gas-mileage-calculator mpg-calculator],
      "data-usage-cost-calculator" => %w[bandwidth-calculator byte-converter subscription-cost-calculator],
      # Everyday budget / life planning
      "wedding-budget-calculator" => %w[engagement-ring-budget-calculator honeymoon-savings-calculator wedding-cost-splitter],
      "student-budget-calculator" => %w[college-cost-comparison-calculator scholarship-roi-calculator tuition-savings-529-calculator],
      "study-time-calculator" => %w[research-paper-word-count-estimator class-schedule-builder gpa-calculator]
    }.freeze
  end
end
