# frozen_string_literal: true

class CalculatorRegistry
  module CrossLinks
    FINANCE = {
      "mortgage-calculator" => %w[home-affordability-calculator amortization-calculator refinance-calculator],
      "loan-calculator" => %w[mortgage-calculator auto-loan-calculator debt-payoff-calculator],
      "compound-interest-calculator" => %w[investment-calculator savings-goal-calculator retirement-calculator],
      "investment-calculator" => %w[compound-interest-calculator retirement-calculator roi-calculator],
      "retirement-calculator" => %w[401k-calculator compound-interest-calculator savings-goal-calculator],
      "pension-calculator" => %w[retirement-calculator 401k-calculator compound-interest-calculator],
      "401k-calculator" => %w[retirement-calculator pension-calculator compound-interest-calculator],
      "fire-calculator" => %w[retirement-calculator savings-goal-calculator compound-interest-calculator],
      "salary-calculator" => %w[tax-bracket-calculator paycheck-calculator inflation-calculator],
      "salary-converter" => %w[salary-calculator hourly-to-salary-calculator paycheck-calculator],
      "hourly-to-salary-calculator" => %w[salary-converter salary-calculator paycheck-calculator],
      "hourly-to-project-calculator" => %w[freelance-rate-calculator hourly-to-salary-calculator side-hustle-calculator],
      "hourly-paycheck-calculator" => %w[paycheck-calculator overtime-calculator hourly-to-salary-calculator],
      "overtime-calculator" => %w[hourly-paycheck-calculator paycheck-calculator work-hours-calculator],
      "paycheck-calculator" => %w[salary-calculator tax-bracket-calculator overtime-calculator],
      "net-pay-calculator" => %w[paycheck-calculator salary-calculator tax-bracket-calculator],
      "tax-bracket-calculator" => %w[paycheck-calculator salary-calculator capital-gains-tax-calculator],
      "capital-gains-tax-calculator" => %w[stock-profit-calculator estate-tax-calculator tax-bracket-calculator],
      "estate-tax-calculator" => %w[inheritance-tax-calculator capital-gains-tax-calculator net-worth-calculator],
      "inheritance-tax-calculator" => %w[estate-tax-calculator capital-gains-tax-calculator net-worth-calculator],
      "sales-tax-calculator" => %w[vat-calculator markup-margin-calculator profit-margin-calculator],
      "vat-calculator" => %w[sales-tax-calculator markup-margin-calculator profit-margin-calculator],
      "side-hustle-calculator" => %w[freelance-tax-calculator freelance-rate-calculator hourly-to-project-calculator],
      "freelance-rate-calculator" => %w[hourly-to-project-calculator freelance-tax-calculator salary-converter],
      "freelance-tax-calculator" => %w[side-hustle-calculator freelance-rate-calculator tax-bracket-calculator],
      "profit-margin-calculator" => %w[roi-calculator break-even-calculator markup-margin-calculator],
      "markup-margin-calculator" => %w[profit-margin-calculator break-even-calculator sales-tax-calculator],
      "break-even-calculator" => %w[profit-margin-calculator markup-margin-calculator saas-metrics-calculator],
      "roi-calculator" => %w[profit-margin-calculator investment-calculator stock-profit-calculator],
      "invoice-generator" => %w[profit-margin-calculator tax-bracket-calculator roi-calculator],
      "detailed-invoice-generator" => %w[invoice-generator profit-margin-calculator break-even-calculator],
      "saas-metrics-calculator" => %w[revenue-per-employee-calculator cost-per-acquisition-calculator startup-runway-calculator],
      "startup-runway-calculator" => %w[saas-metrics-calculator business-loan-calculator revenue-per-employee-calculator],
      "revenue-per-employee-calculator" => %w[saas-metrics-calculator profit-margin-calculator break-even-calculator],
      "cost-per-acquisition-calculator" => %w[cost-per-lead-calculator cost-per-click-calculator saas-metrics-calculator],
      "cost-per-click-calculator" => %w[cost-per-lead-calculator cost-per-acquisition-calculator roi-calculator],
      "cost-per-lead-calculator" => %w[cost-per-acquisition-calculator cost-per-click-calculator roi-calculator],
      "earnings-per-share-calculator" => %w[dividend-yield-calculator stock-profit-calculator roi-calculator],
      "stock-profit-calculator" => %w[roi-calculator dividend-yield-calculator capital-gains-tax-calculator],
      "dividend-yield-calculator" => %w[stock-profit-calculator investment-calculator roi-calculator],
      "dca-calculator" => %w[investment-calculator compound-interest-calculator stock-profit-calculator],
      "crypto-profit-calculator" => %w[stock-profit-calculator roi-calculator capital-gains-tax-calculator],
      "options-profit-calculator" => %w[stock-profit-calculator crypto-profit-calculator roi-calculator],
      "bond-yield-calculator" => %w[dividend-yield-calculator cd-calculator investment-calculator],
      "cd-calculator" => %w[savings-interest-calculator money-market-calculator compound-interest-calculator],
      "money-market-calculator" => %w[cd-calculator savings-growth-calculator savings-interest-calculator],
      "savings-interest-calculator" => %w[savings-growth-calculator compound-interest-calculator cd-calculator],
      "savings-growth-calculator" => %w[compound-interest-calculator savings-interest-calculator cd-calculator],
      "savings-goal-calculator" => %w[savings-per-month-calculator compound-interest-calculator emergency-fund-calculator],
      "savings-per-month-calculator" => %w[savings-goal-calculator emergency-fund-calculator down-payment-calculator],
      "emergency-fund-calculator" => %w[savings-goal-calculator net-worth-calculator savings-per-month-calculator],
      "down-payment-calculator" => %w[mortgage-calculator home-affordability-calculator savings-goal-calculator],
      "net-worth-calculator" => %w[emergency-fund-calculator retirement-calculator savings-goal-calculator],
      "inflation-calculator" => %w[retirement-calculator cost-of-living-calculator salary-calculator],
      "cost-of-living-calculator" => %w[salary-calculator currency-converter rent-affordability-calculator],
      "currency-converter" => %w[cost-of-living-calculator inflation-calculator salary-calculator],
      # Loans by asset
      "auto-loan-calculator" => %w[car-loan-calculator lease-vs-buy-calculator fuel-cost-calculator],
      "car-loan-calculator" => %w[auto-loan-calculator lease-vs-buy-calculator mpg-calculator],
      "motorcycle-loan-calculator" => %w[auto-loan-calculator personal-loan-calculator loan-calculator],
      "rv-loan-calculator" => %w[auto-loan-calculator boat-loan-calculator motorcycle-loan-calculator],
      "boat-loan-calculator" => %w[rv-loan-calculator auto-loan-calculator personal-loan-calculator],
      "lease-vs-buy-calculator" => %w[auto-loan-calculator car-loan-calculator mpg-calculator],
      "personal-loan-calculator" => %w[loan-calculator debt-payoff-calculator credit-card-payoff-calculator],
      "business-loan-calculator" => %w[loan-calculator startup-runway-calculator break-even-calculator],
      "student-loan-calculator" => %w[student-loan-forgiveness-calculator tuition-savings-529-calculator gpa-calculator],
      # Debt
      "debt-payoff-calculator" => %w[debt-snowball-vs-avalanche-calculator credit-card-payoff-calculator personal-loan-calculator],
      "credit-card-payoff-calculator" => %w[debt-payoff-calculator debt-snowball-vs-avalanche-calculator personal-loan-calculator],
      "debt-snowball-vs-avalanche-calculator" => %w[debt-payoff-calculator credit-card-payoff-calculator loan-calculator],
      # Real estate
      "home-affordability-calculator" => %w[mortgage-calculator down-payment-calculator rent-vs-buy-calculator],
      "rent-vs-buy-calculator" => %w[rent-affordability-calculator home-affordability-calculator mortgage-calculator],
      "rent-affordability-calculator" => %w[rent-vs-buy-calculator home-affordability-calculator salary-calculator],
      "amortization-calculator" => %w[mortgage-calculator loan-calculator refinance-calculator],
      "refinance-calculator" => %w[mortgage-calculator heloc-calculator home-equity-loan-calculator],
      "heloc-calculator" => %w[home-equity-loan-calculator mortgage-calculator refinance-calculator],
      "home-equity-loan-calculator" => %w[heloc-calculator refinance-calculator mortgage-calculator],
      "house-flip-calculator" => %w[mortgage-calculator roi-calculator refinance-calculator],
      "fha-mortgage-calculator" => %w[mortgage-calculator va-mortgage-calculator jumbo-mortgage-calculator],
      "va-mortgage-calculator" => %w[mortgage-calculator fha-mortgage-calculator jumbo-mortgage-calculator],
      "jumbo-mortgage-calculator" => %w[mortgage-calculator fha-mortgage-calculator va-mortgage-calculator],
      # Other finance
      "solar-savings-calculator" => %w[electricity-bill-calculator solar-panel-layout-calculator electricity-cost-calculator],
      "tip-pooling-calculator" => %w[tip-calculator overtime-calculator hourly-paycheck-calculator]
    }.freeze
  end
end
