# frozen_string_literal: true

class CalculatorRegistry
  module CrossLinks
    IT_TOOLS = {
      # JSON / YAML / data-format converters
      "json-formatter" => %w[json-validator json-to-yaml-converter json-to-csv-converter],
      "json-validator" => %w[json-formatter regex-tester json-to-typescript-generator],
      "yaml-to-json-converter" => %w[json-to-yaml-converter json-formatter json-validator],
      "json-to-yaml-converter" => %w[yaml-to-json-converter json-formatter json-validator],
      "csv-to-json-converter" => %w[json-to-csv-converter yaml-to-json-converter json-formatter],
      "json-to-csv-converter" => %w[csv-to-json-converter json-formatter csv-to-excel-converter],
      "xml-to-json-converter" => %w[yaml-to-json-converter json-formatter json-validator],
      "json-to-typescript-generator" => %w[json-formatter json-validator json-to-yaml-converter],
      # SQL / Database
      "sql-formatter" => %w[sql-to-nosql-converter json-formatter regex-tester],
      "sql-to-nosql-converter" => %w[sql-formatter json-formatter json-to-typescript-generator],
      "database-size-estimator" => %w[byte-converter bandwidth-calculator api-response-time-calculator],
      # Document / file-format converters
      "csv-to-excel-converter" => %w[excel-to-csv-converter csv-to-pdf-converter csv-to-json-converter],
      "excel-to-csv-converter" => %w[csv-to-excel-converter excel-to-pdf-converter csv-to-json-converter],
      "csv-to-pdf-converter" => %w[csv-to-excel-converter markdown-to-pdf-converter txt-to-pdf-converter],
      "excel-to-pdf-converter" => %w[excel-to-csv-converter csv-to-pdf-converter docx-to-pdf-converter],
      "markdown-to-pdf-converter" => %w[markdown-to-html-converter markdown-preview csv-to-pdf-converter],
      "markdown-to-html-converter" => %w[html-to-markdown-converter markdown-preview markdown-to-pdf-converter],
      "html-to-markdown-converter" => %w[markdown-to-html-converter markdown-preview html-formatter-beautifier],
      "markdown-preview" => %w[markdown-to-html-converter markdown-to-pdf-converter markdown-table-generator],
      "markdown-table-generator" => %w[markdown-preview markdown-to-html-converter json-to-csv-converter],
      "txt-to-pdf-converter" => %w[markdown-to-pdf-converter csv-to-pdf-converter docx-to-pdf-converter],
      "docx-to-pdf-converter" => %w[docx-to-odt-converter odt-to-pdf-converter markdown-to-pdf-converter],
      "docx-to-odt-converter" => %w[odt-to-docx-converter docx-to-pdf-converter odt-to-pdf-converter],
      "odt-to-docx-converter" => %w[docx-to-odt-converter odt-to-pdf-converter docx-to-pdf-converter],
      "odt-to-pdf-converter" => %w[docx-to-pdf-converter odt-to-docx-converter markdown-to-pdf-converter],
      "invoice-pdf-generator" => %w[invoice-generator detailed-invoice-generator csv-to-pdf-converter],
      # Text utilities
      "word-counter" => %w[character-counter words-per-minute-calculator research-paper-word-count-estimator],
      "character-counter" => %w[word-counter words-per-minute-calculator case-converter],
      "case-converter" => %w[character-counter word-counter remove-duplicates],
      "remove-duplicates" => %w[text-diff-checker character-counter case-converter],
      "text-diff-checker" => %w[diff-viewer remove-duplicates character-counter],
      "diff-viewer" => %w[text-diff-checker remove-duplicates word-counter],
      "lorem-ipsum-generator" => %w[fake-data-generator word-counter character-counter],
      "escape-unescape-tool" => %w[html-entity-encoder-decoder url-encoder-decoder string-encoder-decoder],
      "html-entity-encoder-decoder" => %w[escape-unescape-tool url-encoder-decoder html-formatter-beautifier],
      "string-encoder-decoder" => %w[base64-encoder-decoder url-encoder-decoder escape-unescape-tool],
      "plagiarism-calculator" => %w[word-counter citation-generator research-paper-word-count-estimator],
      "citation-generator" => %w[plagiarism-calculator research-paper-word-count-estimator word-counter],
      "morse-code-translator" => %w[base64-encoder-decoder hex-ascii-converter text-to-speech],
      "text-to-speech" => %w[morse-code-translator word-counter character-counter],
      # Encoders / decoders / crypto
      "base64-encoder-decoder" => %w[url-encoder-decoder hex-ascii-converter base64-image-encoder],
      "base64-image-encoder" => %w[base64-encoder-decoder svg-to-png-converter image-resizer],
      "url-encoder-decoder" => %w[base64-encoder-decoder url-parser html-entity-encoder-decoder],
      "hex-ascii-converter" => %w[base64-encoder-decoder base-converter hash-generator],
      "hash-generator" => %w[hmac-generator password-generator secure-random-generator],
      "hmac-generator" => %w[hash-generator jwt-generator password-generator],
      "jwt-decoder" => %w[jwt-generator hash-generator base64-encoder-decoder],
      "jwt-generator" => %w[jwt-decoder hmac-generator hash-generator],
      "text-encryptor" => %w[hash-generator hmac-generator password-generator],
      # Random / identifiers
      "secure-random-generator" => %w[uuid-generator random-number-generator password-generator],
      "uuid-generator" => %w[secure-random-generator hash-generator random-number-generator],
      "password-generator" => %w[password-strength-calculator secure-random-generator hash-generator],
      "fake-data-generator" => %w[lorem-ipsum-generator uuid-generator barcode-generator],
      "barcode-generator" => %w[qr-code-generator fake-data-generator uuid-generator],
      "qr-code-generator" => %w[barcode-generator svg-to-png-converter favicon-generator],
      # Regex
      "regex-tester" => %w[regex-builder regex-explainer json-formatter],
      "regex-builder" => %w[regex-tester regex-explainer string-encoder-decoder],
      "regex-explainer" => %w[regex-tester regex-builder string-encoder-decoder],
      # Web dev / SEO
      "meta-tag-generator" => %w[open-graph-preview schema-markup-generator favicon-generator],
      "favicon-generator" => %w[meta-tag-generator svg-to-png-converter image-resizer],
      "schema-markup-generator" => %w[meta-tag-generator open-graph-preview keyword-density-checker],
      "open-graph-preview" => %w[meta-tag-generator schema-markup-generator keyword-density-checker],
      "keyword-density-checker" => %w[word-counter meta-tag-generator schema-markup-generator],
      "robots-txt-generator" => %w[htaccess-generator meta-tag-generator schema-markup-generator],
      "htaccess-generator" => %w[robots-txt-generator nginx-config-generator dockerfile-generator],
      "csp-header-builder" => %w[cors-header-checker meta-tag-generator ssl-certificate-decoder],
      "cors-header-checker" => %w[csp-header-builder http-header-parser ssl-certificate-decoder],
      # Formatters / beautifiers
      "html-formatter-beautifier" => %w[css-formatter-beautifier javascript-formatter-beautifier code-minifier-beautifier],
      "css-formatter-beautifier" => %w[html-formatter-beautifier javascript-formatter-beautifier code-minifier-beautifier],
      "javascript-formatter-beautifier" => %w[html-formatter-beautifier css-formatter-beautifier code-minifier-beautifier],
      "code-minifier-beautifier" => %w[html-formatter-beautifier css-formatter-beautifier javascript-formatter-beautifier],
      # CSS / design / images
      "color-converter" => %w[color-palette-picker color-contrast-checker css-box-shadow-generator],
      "color-palette-picker" => %w[color-converter color-contrast-checker css-flexbox-generator],
      "color-contrast-checker" => %w[color-converter color-palette-picker meta-tag-generator],
      "css-box-shadow-generator" => %w[css-flexbox-generator color-converter px-to-rem-converter],
      "css-flexbox-generator" => %w[css-box-shadow-generator px-to-rem-converter color-palette-picker],
      "px-to-rem-converter" => %w[css-flexbox-generator css-box-shadow-generator aspect-ratio-calculator],
      "image-resizer" => %w[svg-to-png-converter favicon-generator aspect-ratio-calculator],
      "svg-to-png-converter" => %w[image-resizer favicon-generator qr-code-generator],
      "tailwind-to-css-converter" => %w[css-formatter-beautifier css-flexbox-generator html-to-jsx-converter],
      "html-to-jsx-converter" => %w[html-formatter-beautifier tailwind-to-css-converter javascript-formatter-beautifier],
      # DevOps / containers / Git
      "dockerfile-generator" => %w[docker-compose-generator nginx-config-generator gitignore-generator],
      "docker-compose-generator" => %w[dockerfile-generator nginx-config-generator env-variable-validator],
      "nginx-config-generator" => %w[dockerfile-generator htaccess-generator csp-header-builder],
      "gitignore-generator" => %w[git-commit-message-generator dockerfile-generator semver-bump-calculator],
      "git-commit-message-generator" => %w[gitignore-generator semver-bump-calculator dockerfile-generator],
      "semver-bump-calculator" => %w[git-commit-message-generator gitignore-generator dockerfile-generator],
      "env-variable-validator" => %w[docker-compose-generator dockerfile-generator nginx-config-generator],
      "cron-expression-parser" => %w[cron-job-generator unix-timestamp-converter chmod-calculator],
      "cron-job-generator" => %w[cron-expression-parser unix-timestamp-converter dockerfile-generator],
      "chmod-calculator" => %w[cron-expression-parser dockerfile-generator gitignore-generator],
      # Networking / web infra
      "dns-lookup" => %w[ip-address-lookup mac-address-lookup ssl-certificate-decoder],
      "ip-address-lookup" => %w[dns-lookup mac-address-lookup cidr-subnet-calculator],
      "mac-address-lookup" => %w[ip-address-lookup dns-lookup cidr-subnet-calculator],
      "cidr-subnet-calculator" => %w[ip-address-lookup dns-lookup port-number-reference],
      "ssl-certificate-decoder" => %w[dns-lookup csp-header-builder http-header-parser],
      "url-parser" => %w[url-encoder-decoder http-header-parser curl-to-code-converter],
      "http-header-parser" => %w[url-parser http-status-code-reference cors-header-checker],
      "http-status-code-reference" => %w[http-header-parser url-parser api-response-time-calculator],
      "port-number-reference" => %w[cidr-subnet-calculator ip-address-lookup nginx-config-generator],
      "api-response-time-calculator" => %w[api-rate-limit-calculator bandwidth-calculator uptime-calculator],
      "api-rate-limit-calculator" => %w[api-response-time-calculator uptime-calculator bandwidth-calculator],
      "uptime-calculator" => %w[api-response-time-calculator api-rate-limit-calculator bandwidth-calculator],
      "curl-to-code-converter" => %w[url-parser http-header-parser graphql-query-builder],
      "graphql-query-builder" => %w[curl-to-code-converter json-formatter sql-formatter],
      # Time / productivity
      "unix-timestamp-converter" => %w[time-zone-converter timezone-meeting-planner cron-expression-parser],
      "pomodoro-timer" => %w[stopwatch alarm-timer study-time-calculator],
      "stopwatch" => %w[pomodoro-timer alarm-timer alarm-clock],
      "alarm-timer" => %w[alarm-clock stopwatch pomodoro-timer],
      "alarm-clock" => %w[alarm-timer stopwatch time-zone-converter],
      # Misc utility
      "email-signature-generator" => %w[meta-tag-generator favicon-generator schema-markup-generator],
      # Math / number tools
      "prime-number-checker" => %w[random-number-generator gcd-lcm-calculator base-converter],
      "random-number-generator" => %w[prime-number-checker secure-random-generator uuid-generator],
      "roman-numeral-converter" => %w[base-converter date-difference-calculator base-arithmetic-calculator]
    }.freeze
  end
end
